### ISSUE TITLE
Error when labeling extracted frames, not saved

### ISSUE THREAD

**Issue by Idavr** [DeepLabCut/DeepLabCut#220] opened 2019-02-22 12:47 UTC
**Your Operating system and DeepLabCut version**

Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut2

**Describe the problem**
Trying to demo my own data, and when I get to "Label the extracted frames" I am able to label them, but the labeled images does not get saved. 

This is the error I get:
```
RuntimeError                              Traceback (most recent call last)
/home/poop/anaconda3/envs/DeepLabCut2/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    303                 pass
    304             else:
--> 305                 return printer(obj)
    306             # Finally look for special method names
    307             method = get_real_method(obj, self.print_method)

/home/poop/anaconda3/envs/DeepLabCut2/lib/python3.6/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    237 
    238     if 'png' in formats:
--> 239         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    240     if 'retina' in formats or 'png2x' in formats:
    241         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

/home/poop/anaconda3/envs/DeepLabCut2/lib/python3.6/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    121 
    122     bytes_io = BytesIO()
--> 123     fig.canvas.print_figure(bytes_io, **kw)
    124     data = bytes_io.getvalue()
    125     if fmt == 'svg':

/home/poop/anaconda3/envs/DeepLabCut2/lib/python3.6/site-packages/matplotlib/backends/backend_wx.py in print_figure(self, filename, *args, **kwargs)
    831         # determining things like bounding boxes.
    832         if self._isDrawn:
--> 833             self.draw()
    834 
    835     def _onPaint(self, evt):

/home/poop/anaconda3/envs/DeepLabCut2/lib/python3.6/site-packages/matplotlib/backends/backend_wxagg.py in draw(self, drawDC)
     39         self.bitmap = _convert_agg_to_wx_bitmap(self.get_renderer(), None)
     40         self._isDrawn = True
---> 41         self.gui_repaint(drawDC=drawDC, origin='WXAgg')
     42 
     43     def blit(self, bbox=None):

/home/poop/anaconda3/envs/DeepLabCut2/lib/python3.6/site-packages/matplotlib/backends/backend_wx.py in gui_repaint(self, drawDC, origin)
    799         """
    800         DEBUG_MSG("gui_repaint()", 1, self)
--> 801         if self.IsShownOnScreen():
    802             if not drawDC:
    803                 # not called from OnPaint use a ClientDC

RuntimeError: wrapped C/C++ object of type FigureCanvasWxAgg has been deleted

<Figure size 1073x844 with 2 Axes>
```

The program creates a .csv and.h5 file in the correct folder with the extracted frames, but it seems like the labeled frames gets immediately deleted. I thought it might have to do with the size of the pictures, but the frames themselves are smaller than the 850x850 you mention at this step. Is there a way to fix this issue?

Thank you for all the work and help given, so far this tool seems awesome!

**Comment by MMathisLab** [comment] 2019-02-22 16:55
>> The program creates a .csv and.h5 file in the correct folder with the extracted frames, but it seems like the labeled frames gets immediately deleted.

I'm not sure what you mean -  if the .h5 and .csv are saved, then the labels are indeed saved... I don't know how it could delete you original images... there are no "labeled frames" made in this step. If you want to plot your points over the image, you need to run ``deeplabcut.check_labels(``


Regarding the error message, can you tell me what this imput puts out for you?

```
     In [8]: import matplotlib
      In [9]: matplotlib.__version__
     Out[9]: '2.2.2'
```

**Comment by Idavr** [comment] 2019-02-24 08:40
I am so sorry, the error message threw me off! I have now created the labeled images, now trying to figure out how to run the program from the Docker. So sorry, I am still quite new to this. Should I just run the commands in the terminal? If so, the train_network command is not recognized, and when trying to import deeplabcut is get

    import: not authorized `deeplabcut' @ error/constitute.c/WriteImage/1028.

When running the import matplotlib with Notebook, I get the same ouput as you've shown, with version 2.2.2. How come?

**Comment by MMathisLab** [comment] 2019-02-24 16:13
Great! I’ll close this issue then, as it’s resolved; maybe ask your question on the forum regarding running steps since not a bug report: https://forum.image.sc/tags/deeplabcut. I highly recommend starting not in Docker if you are new to Docker. 

Run through the tutorials first, and check out the YouTube videos: https://www.youtube.com/watch?v=7xwOhUcIGio 

:)

**Closed as completed by MMathisLab** 2019-02-24 16:13 UTC
Labels: question

**Comment by Idavr** [comment] 2019-02-25 12:05
Thank you very much, the tutorial made a lot of things clear :)
