### ISSUE TITLE
IndexError in 2.2rc2 when identity: true

### ISSUE THREAD

**Issue by mynschen** [DeepLabCut/DeepLabCut#1290] opened 2021-05-31 16:14 UTC
**Describe the bug**

I am training a network with videos containing two mice which look different. In the config.yaml I set identity: true and applied the default DLCRnet. When I train the network through gui, it shows IndexError: list index out of range. Then it stuck at “starting multi-animal training” and do not proceed. The question is present only if Identity is set as true. 
One more thing I am not sure if it is relevant to this issue: I defined 15 bodyparts but not all of them were labeled in each frame. For example, if right hand is occluded, I skipped that body part and continue to label the next.

**Desktop (please complete the following information about your system):**
 - OS: Ubuntu20.04
 - DeepLabCut Version: 2.2rc2
 - DeepLabCut mode: multi-animal tracking

**To Reproduce**
As described in the bug

<details><summary>TRACEBACK</summary><p>

```python

^do not delete the above "<details><summary>TRACEBACK</summary><p>" or the ```python part!
PLACE YOUR CODE HERE!!!  
do not delete below this line, leave the blank line and the ```

```
</p></details>

**Expected behavior**
Proceeds to training

**Screenshots**
If applicable, add screenshots to help explain your problem. (but please post the code output above, not images of code!)
![image](https://user-images.githubusercontent.com/53803897/120219662-2782b280-c26e-11eb-803b-14d563a5f942.png)

**Additional context**

Thank you so much!

**Comment by bobfromjapan** [comment] 2021-06-01 02:05
I am also seeing the same error. Thanks for creating the issue!

I have found that this problem occurs in a bit of a special case, when there is more than one animal that has no markings at all.
This can be caused by one animal being in a remote location and being eliminated by cropping, which is part of the multi-animal tracking flow.

If there is no marking, the `get_batch` function (L168-170) in `pose_estimation_tensorflow\dataset\pose_multianimal_imgaug.py` create `joint_points` as an array shorter than the Max_number of the animal in the videos.

```
joint_points = np.concatenate(
    [Joints[person_id][:, 1:3] for person_id in Joints.keys()]
    )
```
I think this caused out-of-array references when doing `compute_target_part_scoremap_numpy` function (L393).

```
joint_ids = joint_id[person_id].copy()
```

Maybe I'm totally missing the point, in which case, please ignore it! I hope this is helpful.

**Comment by jeylau** [comment] 2021-06-01 07:37
That's correct @bobfromjapan! I'm really sorry I let this pass, but I'll push a fix and stricter tests soon 😕

**Comment by mynschen** [comment] 2021-06-01 12:08
Wow! How amazing that the issue is so efficiently handled!
Thank you @bobfromjapan and @jeylau !

**Comment by jeylau** [comment] 2021-06-01 15:36
Sorry about it @mynschen @bobfromjapan, but this should finally be fixed with #1297. If you guys want to try it, please let me know if training runs properly 😅

**Closed as completed** 2021-06-02 10:45 UTC

**Comment by bobfromjapan** [comment] 2021-06-02 11:02
Hi @jeylau !

I have used `identity_tests` branch today, and it worked completely with my dataset! I was able to perform standard training and video analysis with no problem using multi-animal & Identity=True.
Thank you for your great work!!

But, actually, I encountered another IndexError with `assemble with identity only` option in analysis videos. 
I don't know enough about the cause of the problem yet, so I might raise an Issue after some investigation(it might be a problem with my data set!).

Best Regard,

**Comment by MMathisLab** [comment] 2021-06-02 14:52
@bobfromjapan thanks so much for the sponsor 💖

**Comment by mynschen** [comment] 2021-06-03 13:08
Thank you @jeylau and @bobfromjapan !
The training with identity works smoothly now!

Just that:
If Calibrate animal assembly=Yes (No matter if Assembly with identity only=Yes/No)
then an numpy.linalig.LinAlgError occurs in convert2_tracklets in analyze_videos.py
Would be wonderful to figure out why!

Despite the remaining bug, I really want to express my respect! The identity switch in Identity=False were all gone now! Magic!

**Comment by mynschen** [comment] 2021-06-03 13:09
The screenshot of the numpy.linalig.LinAlgError mentioned above:
![image](https://user-images.githubusercontent.com/53803897/120649984-ed085800-c4af-11eb-9526-4d31224866d9.png)

**Comment by jeylau** [comment] 2021-06-03 13:21
Looks like your labeled data may be too sparse to robustly determine the prior "skeleton distribution". Keep it turned off then, and I'll make sure to catch this error so it is more informative to the user. 😅

**Comment by mynschen** [comment] 2021-06-03 15:08
Extremely helpful to know! I will try to leave no bodypart unlabelled and report back here. (Might take days though 🤣)
Thanks a lot~👍

**Comment by MMathisLab** [comment] 2021-06-04 09:34
Hey @mynschen just as a reminder, more body parts are better to make a robust graph; so even if you want to track just 4 points on a mouse, I would recommend using more (i.e., we do 12); so you can NOT label points that are occluded, but have more body parts :D

**Comment by mynschen** [comment] 2021-06-04 09:41
I'm using 15 bodyparts but mostly 9-10 are labelled. Will try. Thanks for the kind reminder!
