### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by LeonardKarsunky** [DeepLabCut/DeepLabCut#256] opened 2019-04-02 13:49 UTC
**Operating system and DeepLabCut version**
MacOS Mojave 10.14.3, with an Anaconda Env, & DeepLabCut 2.0.

**Describe the problem**
When I run the command to extract my frames "deeplabcut.extract_frames(path_config, 'automatic', 'kmeans')", it causes this problem:

AttributeError                            Traceback (most recent call last)
<ipython-input-3-caf2905c8f6f> in <module>()
----> 1 deeplabcut.extract_frames(path_config, 'automatic', 'kmeans')

/Users/leonardkarsunky/Documents/Bachelor Project 2019/DeepLabCut/deeplabcut/generate_training_dataset/frame_extraction.py in extract_frames(config, mode, algo, crop, userfeedback, cluster_step, cluster_resizewidth, cluster_color, opencv)
    111             raise Exception("Perhaps consider extracting more, or a natural number of frames.")
    112 
--> 113         videos = cfg['video_sets'].keys()
    114         if opencv:
    115             import cv2

AttributeError: 'NoneType' object has no attribute 'keys'

**How to Reproduce the problem**
The only steps I did were:
1. import deeplabcut
2. deeplabcut.create_new_project('WhiskerTracking_SC016c_2', 'karsunky', ['leonardkarsunky/Documents/Bachelor\ Project\ 2019/SC016c_2'])
3. path_config = '/Users/leonardkarsunky/Documents/Bachelor Project 2019/DeepLabCut/WhiskerTracking_SC016c_2-karsunky-2019-03-12/config.yaml'
4. deeplabcut.extract_frames(path_config, 'automatic', 'kmeans')

If anyone can help it would be greatly appreciated!

**Comment by MMathisLab** [comment] 2019-04-02 14:28
This line will need to include a video (ie with an ending like .avi or .mp4), also be sure your slashes are consistent: 

deeplabcut.create_new_project('WhiskerTracking_SC016c_2', 'karsunky', ['leonardkarsunky/Documents/Bachelor\ Project\ 2019/SC016c_2'])

This is why it finds no video, per the error message :)

**Comment by LeonardKarsunky** [comment] 2019-04-02 19:23
Thanks for noticing that.
This time I changed the name "Bachelor\ Project\ 2019" to "Bachelor_Project_2019" and added the .avi extension, but when I call "deeplabcut.extract_frames" it seems to go on forever and never terminate.
Any tips? Thanks

**Comment by MMathisLab** [comment] 2019-04-03 12:35
I cannot troubleshoot effectively without the full call and output. Since the first project you created would be corrupt, I would delete that folder and start again. It also seems the paths are not correctly formatted ie. This should be video = [‘/home/user/desktop/myvideo.avi’] I also don’t know how you edited your config file, ie # frames to extract, how long your video is, are you using color, cropping, etc. since this is not a bug report I’ll close the issue, but feel free to post here with more details.

**Closed as completed by MMathisLab** 2019-04-03 12:35 UTC

**Comment by LeonardKarsunky** [comment] 2019-04-03 20:46
Thanks, I changed the path of the video to ['/Users/leonardkarsunky/Documents/Bachelor\ Project\ 2019/SC016c_2'] and extract_frames seems to have worked. Also for info I'm using a 30 second video, 200 fps, 128x128 video resolution, no color, and no cropping I believe. In the config.yaml file I have only "Whisker" as body part and I put 20 number of frames to pick.
However now I have a problem with label_frames, and I get this error (starting from extract_frames):

In [5]: deeplabcut.extract_frames(path_config,'automatic','kmeans')
Config file read successfully.
Do you want to extract (perhaps additional) frames for video: /Users/leonardkarsunky/Documents/Bachelor_Project_2019/SC016c_2.avi ?
yes/noyes
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 30.0  seconds.
Extracting and downsampling... 6000  frames from the video.
6000it [00:00, 7177.35it/s]
Kmeans clustering ... (this might take a while)

Frames were selected.
You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).

In [6]: deeplabcut.label_frames(path_config)
An exception has occurred, use %tb to see the full traceback.

SystemExit: This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.

/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2855: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [7]:                                                                                                                                                      
Traceback (most recent call last):
  File "/anaconda3/envs/dlc-macOS-CPU/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 353, in start
    self.shell.mainloop()
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 459, in mainloop
    self.interact()
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 442, in interact
    code = self.prompt_for_code()
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 355, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 415, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 102, in run
    self._inputhook_context.call_inputhook(ready)
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/prompt_toolkit/eventloop/inputhook.py", line 74, in call_inputhook
    self.inputhook(self)
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 474, in inputhook
    self._inputhook(context)
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/IPython/terminal/pt_inputhooks/wx.py", line 75, in inputhook_wx2
    assert wx.Thread_IsMain()
AttributeError: module 'wx' has no attribute 'Thread_IsMain'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by MMathisLab** [comment] 2019-04-03 21:38
Yeah you have to use a framework build of python, namely ``pythonw `` - plesae see here: https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips

New! As of 2.0.5 MacOS is supported! For previous versions, MacOS was not supported. See here: https://github.com/AlexEMG/DeepLabCut/issues/101#issuecomment-437628340, and here: https://github.com/AlexEMG/DeepLabCut/issues/141


and here: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/UseOverviewGuide.md#option-2-using-terminal-start-python

Option 2: using terminal, Start Python:

Open an ipython session and import the package by typing in the terminal: Please note, if you are using MacOS, you must use pythonw vs. ipython (also, GUIs are not supported in Jupyter in MacOS so please follow the instructions below!)

Namely, when you open terminal you need to activate your env then start as such:
```
pythonw
import deeplabcut
```

**Comment by LeonardKarsunky** [comment] 2019-04-06 14:37
Yes it works now thanks for the help!

**Comment by ChangQing-SH** [comment] 2019-06-10 07:01
@MMathisLab I encounter  the same issue: 'module 'wx' has no attribute 'Thread_IsMain'' when using ipython, 
MacOS High Serria with an Anaconda Env, & DeepLabCut 2.0.6,(using dlc-macOS-CPU.yaml)

I also tried the pythonw, it can open labing GUI, but i can't mark it, others button works well.

**Comment by MMathisLab** [comment] 2019-06-10 13:06
Yes for Mac you must use pythonw 

Did you right click to label? It works for me....

**Comment by ChangQing-SH** [comment] 2019-06-11 04:07
> Yes for Mac you must use pythonw
> 
> Did you right click to label? It works for me....

Thanks for your quick reply, finally I figure it out.  I have successfully run deeplabcut with openfield video under the examples,
Can you give me some suggestions with my own case: the tail suspension test.
There are four mice, the 2nd one will be tested 1min later after the 1st one, and so on. I don't know how to handle this, What I do is that I created 4 sets labels (total 12 labels), but the result is weird. When it just test the first one, all the labels were marked on this mouse.
<img width="300" alt="Screen Shot 2019-06-11 at 12 04 23 PM" src="https://user-images.githubusercontent.com/48444988/59243188-3b781880-8c41-11e9-9081-13ffc66a9be7.png">
<img width="300" alt="Screen Shot 2019-06-11 at 12 04 34 PM" src="https://user-images.githubusercontent.com/48444988/59243214-59de1400-8c41-11e9-8296-1060e8581553.png">
