### ISSUE TITLE
Failed Installation due to missing directories 

### ISSUE THREAD

**Issue by CyclicCurrent03** [DeepLabCut/DeepLabCut#2336] opened 2023-07-29 17:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I start with:
```
wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-MacOSX-arm64.sh -O ~/miniconda.sh
bash ~/miniconda.sh -b -p $HOME/miniconda
source ~/miniconda/bin/activate
conda init zsh
```

works and installs miniconda on my mac. Following step two from here: [https://deeplabcut.github.io/DeepLabCut/docs/installation.html](url)

I carry out in the terminal window: 
```
git clone https://github.com/DeepLabCut/DeepLabCut.git
cd DeepLabCut/conda-environments
conda env create -f DEEPLABCUT_M1.yaml
```

which produces the error seen below.

I then run: `conda activate DEEPLABCUT_M1`
and it activates just fine (I get the correct format of DEEPLABCUT_M1 (USER)@(USER'S)-MBP conda-environments

Then, running python -m deeplabcut leads to: /Library/Developer/CommandLineTools/usr/bin/python3: No module named deeplabcut

`/Library/Developer/CommandLineTools/usr/bin/python3: No module named deeplabcut`

### Operating System

Mac M1

### DeepLabCut version

Latest Version

### DeepLabCut mode

single animal

### Device type

CPU

### Steps To Reproduce

conda env create -f DEEPLABCUT_M1.yaml

### Relevant log output

```shell
| /Users/(USER)/miniconda/envs/DEEPLABCUT_M1/bin/.nb_conda-post-link.sh: line 2: /Users/(USER)/miniconda/envs/DEEPLABCUT_M1/bin/jupyter-nbextension: No such file or directory
/Users/(USER)/miniconda/envs/DEEPLABCUT_M1/bin/.nb_conda-post-link.sh: line 3: /Users/(USER)/miniconda/envs/DEEPLABCUT_M1/bin/jupyter-serverextension: No such file or directory

done
ERROR conda.core.link:_execute(730): An error occurred while installing package 'conda-forge::nb_conda-2.2.1-unix_6'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::nb_conda-2.2.1-unix_6
location of failed script: /Users/(USER)/miniconda/envs/DEEPLABCUT_M1/bin/.nb_conda-post-link.sh
==> script messages <==
/Users/(USER)/miniconda/envs/DEEPLABCUT_M1/bin/.nb_conda-post-link.sh: line 2: /Users/(USER)/miniconda/envs/DEEPLABCUT_M1/bin/jupyter-nbextension: No such file or directory
/Users/(USER)/miniconda/envs/DEEPLABCUT_M1/bin/.nb_conda-post-link.sh: line 3: /Users/(USER)/miniconda/envs/DEEPLABCUT_M1/bin/jupyter-serverextension: No such file or directory
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by lxspedeza** [comment] 2023-07-31 09:58
I receive a similar error message and the installation fails completely, the conda environment is created but it's empty.
I'm on Win10, using Anaconda Navigator / Anaconda prompt as admin. 
![error installing dlc](https://github.com/DeepLabCut/DeepLabCut/assets/24687135/0893ef88-5053-4c19-9cc8-40e4b86471e7)

**Comment by Ruoqi277** [comment] 2023-08-01 00:59
> 

same

**Comment by lxspedeza** [comment] 2023-08-01 08:06
In the end, I found something on this forum which I can't link because I'm mobile bound now. Anyway, you open the DEEPLABCUT.yaml file from the Conda-environments folder and add this line to the dependencies:
- notebook <7.0.0

Also, I deleted the cudnn part in dependencies, and now it works.
I also conda installed the cudnn version I needed inside the DeepLabCut Conda environment after installing DLC to be safe.

**Comment by Ruoqi277** [comment] 2023-08-04 19:19
> In the end, I found something on this forum which I can't link because I'm mobile bound now. Anyway, you open the DEEPLABCUT.yaml file from the Conda-environments folder and add this line to the dependencies:
> 
> * notebook <7.0.0
> 
> Also, I deleted the cudnn part in dependencies, and now it works. I also conda installed the cudnn version I needed inside the DeepLabCut Conda environment after installing DLC to be safe.

Thank you so much !
It works on my window10, but on mac it still doesn't work

**Comment by n-poulsen** [comment] 2023-08-07 07:25
Duplicate of #2322

**Closed as not planned by n-poulsen** 2023-08-07 07:25 UTC
Labels: duplicate
