### ISSUE TITLE
Error after saving labels

### ISSUE THREAD

**Issue by akeip** [DeepLabCut/DeepLabCut#1648] opened 2022-01-21 23:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi there,

When I try to save labels I receive this error message: ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables. Which prevents me to advancing to any of the downstream steps. I've included the full log output from creating the project up until the error occurs. I've tried a number of troubleshooting solutions, but none have worked. I've include links to the proposed solutions that I've attempted in the 'Anything Else' textbox.

Thanks for your help!!
Alex

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.2.0.5

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 2070 with Max-Q Design

### Relevant log output

```shell
(base) C:\Users\keipa>conda activate DEEPLABCUT

(DEEPLABCUT) C:\Users\keipa>ipython
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut

In [2]: deeplabcut.create_new_project(
   ...:     "TEST",
   ...:     "KEIP",
   ...:     ["D:\\Test_Video_Trimmed.M4V"],
   ...:     working_directory="C:\\Users\\keipa\\Downloads\\DeepLabCut-master\\DeepLabCut-master\\conda-environments",
   ...:     copy_videos=False,
   ...:     multianimal=False,
   ...: )
Created "C:\Users\keipa\Downloads\DeepLabCut-master\DeepLabCut-master\conda-environments\TEST-KEIP-2022-01-21\videos"
Created "C:\Users\keipa\Downloads\DeepLabCut-master\DeepLabCut-master\conda-environments\TEST-KEIP-2022-01-21\labeled-data"
Created "C:\Users\keipa\Downloads\DeepLabCut-master\DeepLabCut-master\conda-environments\TEST-KEIP-2022-01-21\training-datasets"
Created "C:\Users\keipa\Downloads\DeepLabCut-master\DeepLabCut-master\conda-environments\TEST-KEIP-2022-01-21\dlc-models"
Attempting to create a symbolic link of the video ...
Created the symlink of D:\Test_Video_Trimmed.M4V to C:\Users\keipa\Downloads\DeepLabCut-master\DeepLabCut-master\conda-environments\TEST-KEIP-2022-01-21\videos\Test_Video_Trimmed.M4V
C:\Users\keipa\Downloads\DeepLabCut-master\DeepLabCut-master\conda-environments\TEST-KEIP-2022-01-21\videos\Test_Video_Trimmed.M4V
Generated "C:\Users\keipa\Downloads\DeepLabCut-master\DeepLabCut-master\conda-environments\TEST-KEIP-2022-01-21\config.yaml"

A new project with name TEST-KEIP-2022-01-21 is created at C:\Users\keipa\Downloads\DeepLabCut-master\DeepLabCut-master\conda-environments and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
Out[2]: 'C:\\Users\\keipa\\Downloads\\DeepLabCut-master\\DeepLabCut-master\\conda-environments\\TEST-KEIP-2022-01-21\\config.yaml'

In [3]: deeplabcut.extract_frames(
   ...:     "C:\\Users\\keipa\\Downloads\\DeepLabCut-master\\DeepLabCut-master\\conda-environments\\TEST-KEIP-2022-01-21\\config.YAM
   ...: L",
   ...:     mode="automatic",
   ...:     algo="kmeans",
   ...:     userfeedback=False,
   ...:     crop=False,
   ...: )
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 718.4  seconds.
Extracting and downsampling... 14368  frames from the video.
14368it [00:23, 615.45it/s]
Kmeans clustering ... (this might take a while)
C:\Users\keipa\anaconda3\envs\DEEPLABCUT\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 3072 or by setting the environment variable OMP_NUM_THREADS=1
  warnings.warn(
Frame 14357  not found!
Frames were successfully extracted, for the videos listed in the config.yaml file.

You can now label the frames using the function 'label_frames' (Note, you should label frames extracted from diverse videos (and many videos; we do not recommend training on single videos!)).

In [4]: deeplabcut.label_frames(
   ...:     "C:\\Users\\keipa\\Downloads\\DeepLabCut-master\\DeepLabCut-master\\conda-environments\\TEST-KEIP-2022-01-21\\config.YAM
   ...: L"
   ...: )
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\labeling_toolbox.py:945, in MainFrame.saveDataSet(self, event)
    937 self.dataFrame = self.dataFrame.reindex(
    938     self.cfg["bodyparts"],
    939     axis=1,
    940     level=self.dataFrame.columns.names.index("bodyparts"),
    941 )
    942 self.dataFrame.to_csv(
    943     os.path.join(self.dir, "CollectedData_" + self.scorer + ".csv")
    944 )
--> 945 self.dataFrame.to_hdf(
    946     os.path.join(self.dir, "CollectedData_" + self.scorer + ".h5"),
    947     "df_with_missing",
    948 )

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\generic.py:2703, in NDFrame.to_hdf(self, path_or_buf, key, mode, complevel, complib, append, format, index, min_itemsize, nan_rep, dropna, data_columns, errors, encoding)
   2592 """
   2593 Write the contained data to an HDF5 file using HDFStore.
   2594
   (...)
   2699 >>> os.remove('data.h5')
   2700 """
   2701 from pandas.io import pytables
-> 2703 pytables.to_hdf(
   2704     path_or_buf,
   2705     key,
   2706     self,
   2707     mode=mode,
   2708     complevel=complevel,
   2709     complib=complib,
   2710     append=append,
   2711     format=format,
   2712     index=index,
   2713     min_itemsize=min_itemsize,
   2714     nan_rep=nan_rep,
   2715     dropna=dropna,
   2716     data_columns=data_columns,
   2717     errors=errors,
   2718     encoding=encoding,
   2719 )

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\io\pytables.py:311, in to_hdf(path_or_buf, key, value, mode, complevel, complib, append, format, index, min_itemsize, nan_rep, dropna, data_columns, errors, encoding)
    309 path_or_buf = stringify_path(path_or_buf)
    310 if isinstance(path_or_buf, str):
--> 311     with HDFStore(
    312         path_or_buf, mode=mode, complevel=complevel, complib=complib
    313     ) as store:
    314         f(store)
    315 else:

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\io\pytables.py:572, in HDFStore.__init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    569 if "format" in kwargs:
    570     raise ValueError("format is not a defined argument for HDFStore")
--> 572 tables = import_optional_dependency("tables")
    574 if complib is not None and complib not in tables.filters.all_complibs:
    575     raise ValueError(
    576         f"complib only supports {tables.filters.all_complibs} compression."
    577     )

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\compat\_optional.py:118, in import_optional_dependency(name, extra, errors, min_version)
    116 except ImportError:
    117     if errors == "raise":
--> 118         raise ImportError(msg) from None
    119     else:
    120         return None

ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.
You can now check the labels, using 'check_labels' before proceeding. Then, you can use the function 'create_training_dataset' to create the training dataset.
```

### Anything else?

https://github.com/DeepLabCut/DeepLabCut/issues/431

https://github.com/DeepLabCut/DeepLabCut/issues/377

https://github.com/DeepLabCut/DeepLabCut/issues/398

https://github.com/DeepLabCut/DeepLabCut/issues/108

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment] 2022-01-24 13:45
Duplicate of #1642, #1575, #1637

This command should do the trick `pip install tables==3.6.1`. Feel free to reopen the issue if it didn't work though.

**Closed as completed by jeylau** 2022-01-24 13:45 UTC
Labels: duplicate, Installation
