### ISSUE TITLE
Inquiry on predict.py for multiple body part prediction

### ISSUE THREAD

**Issue by cvKDean** [DeepLabCut/DeepLabCut#125] opened 2018-11-20 03:26 UTC
Good day,

DeepLabCut is working really great for detecting features in my current project. Thank you very much for your excellent work. I am currently using the Nature Neuroscience version (v1.1) but will get around to checking out the newer version soon.

For now, I would like to ask a question regarding multiple feature and pose prediction. From one closed issue, it was explained that line 28 from pose-tensorflow/nnet/predict.py can be modified to change the number of body parts to be identified. 
https://github.com/AlexEMG/DeepLabCut/blob/1.11/pose-tensorflow/nnet/predict.py#L28
If I'm not mistaken the exact line is as follows: 
`scmap = outputs_np[0]`

I understand that outputs_np[0] returns the best peak for a particular feature at a time (i.e. nose), however I'm not sure how to get the 2 or 3 highest peaks. If it is changed to: 
`scmap = outputs_np[1]` 
it should just return the second highest peak. Thus, should it be something like 
`scmap = outputs_np[0], outputs_np[1]`? Or instantiating a separate variable like
`scmap1 = outputs_np[0], scmap1 = outputs_np[1]`

Thank you very much.
-Dean

**Comment by MMathisLab** [comment] 2018-11-20 05:10
Hi Dean, thanks for using it, we’re glad you like it. So what you want to do is save the scoremaps, then threshold (find multiple peaks) them to find multiple labels. As we mentioned issue #84 ... and some of this was discussed in the slack group, since it’s not a bug so we like to keep development discussions on slack (anyone is open to join). 

here is the script that will save the scoremaps when you analyze the videos. https://github.com/AlexEMG/DeepLabCut/blob/1.11/Analysis-tools/AnalyzeVideosAndExtractScoreMaps.py

(at this stage you need to use DLC 1.1 for this)

But we don’t have a plan to push code for this right now... as this is a feature request I’ll close the issue, but feel free to join slack to discuss developments. 

Hope that helps!

**Closed as completed by MMathisLab** 2018-11-20 05:10 UTC
Labels: Feature-request
