### ISSUE TITLE
Problem in testscript

### ISSUE THREAD

**Issue by smart2pet** [DeepLabCut/DeepLabCut#2082] opened 2022-12-11 06:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The log is under it.

Loading DLC 2.2.3...
Imported DLC!
On Windows/OSX tensorpack is not tested by default.
CREATING PROJECT
Project "D:\zry\python\AI\pet_activities_classification\DeepLabCut\examples\TEST-Alex-2022-12-11" already exists!
EXTRACTING FRAMES
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 8.53  seconds.
Extracting and downsampling... 256  frames from the video.
256it [00:01, 141.10it/s]
Kmeans clustering ... (this might take a while)
C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
Frames were successfully extracted, for the videos listed in the config.yaml file.

You can now label the frames using the function 'label_frames' (Note, you should label frames extracted from diverse videos (and many videos; we do not recommend training on single videos!)).
CREATING-SOME LABELS FOR THE FRAMES
Plot labels...
Creating images with labels by Alex.
Traceback (most recent call last):
  File ".\testscript.py", line 122, in <module>
    deeplabcut.check_labels(path_config_file)
  File "C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 355, in check_labels
    visualization.make_labeled_images_from_dataframe(
  File "C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\visualization.py", line 307, in make_labeled_images_from_dataframe
    h, w = ic[0].shape[:2]
  File "C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\skimage\io\collection.py", line 294, in __getitem__
    self.data[idx] = self.load_func(self.files[n], **kwargs)
  File "C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 15, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\imageio\v2.py", line 226, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\imageio\core\imopen.py", line 298, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `D:\zry\python\AI\pet_activities_classification\DeepLabCut\examples\TEST-Alex-2022-12-11\labeled-data\reachingvideo1\CollectedData_Alex.csv`` with iomode `ri`.

### Operating System

Windows

### DeepLabCut version

2.2.3

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

You just need run examples/testscript.py

### Relevant log output

```shell
Loading DLC 2.2.3...
Imported DLC!
On Windows/OSX tensorpack is not tested by default.
CREATING PROJECT
Project "D:\zry\python\AI\pet_activities_classification\DeepLabCut\examples\TEST-Alex-2022-12-11" already exists!
EXTRACTING FRAMES
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 8.53  seconds.
Extracting and downsampling... 256  frames from the video.
256it [00:01, 141.10it/s]
Kmeans clustering ... (this might take a while)
C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
Frames were successfully extracted, for the videos listed in the config.yaml file.

You can now label the frames using the function 'label_frames' (Note, you should label frames extracted from diverse videos (and many videos; we do not recommend training on single videos!)).
CREATING-SOME LABELS FOR THE FRAMES
Plot labels...
Creating images with labels by Alex.
Traceback (most recent call last):
  File ".\testscript.py", line 122, in <module>
    deeplabcut.check_labels(path_config_file)
  File "C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 355, in check_labels
    visualization.make_labeled_images_from_dataframe(
  File "C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\visualization.py", line 307, in make_labeled_images_from_dataframe
    h, w = ic[0].shape[:2]
  File "C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\skimage\io\collection.py", line 294, in __getitem__
    self.data[idx] = self.load_func(self.files[n], **kwargs)
  File "C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 15, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\imageio\v2.py", line 226, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "C:\Users\zhang\.conda\envs\DEEPLABCUT\lib\site-packages\imageio\core\imopen.py", line 298, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `D:\zry\python\AI\pet_activities_classification\DeepLabCut\examples\TEST-Alex-2022-12-11\labeled-data\reachingvideo1\CollectedData_Alex.csv`` with iomode `ri`.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by smart2pet** [comment] 2022-12-11 06:33
I'm need to use tomorrow so please fastly fix it or tell me how to solve it.Thanks a lot.

**Comment by jeylau** [comment] 2022-12-12 08:57
Duplicate of https://github.com/DeepLabCut/DeepLabCut/issues/1827

This is a rare, obscure error sometimes showing on Windows when exclusively when running the test script. Try DeepLabCut with your own data, and everything should work ☺️

**Closed as completed by jeylau** 2022-12-12 08:57 UTC

**Comment by jonahpearl** [comment] 2023-04-25 23:21
This happens, to me at least, when I run the test script for a second time with the test data already downloaded. Deleting the `Testcore-Mackenzie-2023-04-25` folder and letting it re-download solves the issue.
