### ISSUE TITLE
CUDA acceleration during video analysis fails in 'second' pass

### ISSUE THREAD

**Issue by VAmoroso13** [DeepLabCut/DeepLabCut#2546] opened 2024-03-21 21:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I searched, but didn't find an issue quite like this one. Generally people don't get any GPU acceleration because of a mismatch between CUDA/CuDNN/TF2.10 or such. I get GPU/CUDA acceleration as you can see below then it fails subsequently, leading me to believe it's not a simple mismatch. I tried uninstalling and reinstalling in all different combinations of old versions. 

I returned to Win11 to use DLC two days ago, updated to DLC2.3.9. Was prompted to update nvidia drivers to [551.86] and find that I get CUDA acceleration during the 'first' pass of video analysis, but then it defaults to CPU. 

Note the speed difference in the different computational passes:

![Screenshot 2024-03-22 045825](https://github.com/DeepLabCut/DeepLabCut/assets/108757663/f5133127-a0bd-4a50-a049-f94c1c7f3fea)

This is confirmed by [nvidia-smi] which shows no activity on either GPU:

![Screenshot 2024-03-22 050049](https://github.com/DeepLabCut/DeepLabCut/assets/108757663/d427d2a7-b9f5-4468-9c48-b5f0b1279895)

I electronically turned off one of the GPUs in the driver to no avail. Have tried uninstalling and reinstalling CUDA and CuDNN in any number of combinations. At present I have:

> 2xRTX4080s
> CUDA 11.8 and 12.3
> CuDNN 8.9.2.26 for version 11

Any help would be greatly appreciated!

### Operating System

Windows 11 22H2

### DeepLabCut version

2.3.9

### DeepLabCut mode

multi animal

### Device type

RTX4080 x2

### Steps To Reproduce

Analyse a video and see reduced speed after first pass

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by VAmoroso13** [comment] 2024-03-25 18:17
Just an update. 

I reformatted and reinstalled windows 11 after several days of annoyance only to see that it will not work at all in the GUI. That said, the following reports a correct use of cuda in tensorflow:

```
import tensorflow as tf
print("Num GPUs Available: ", len(TF.config.list_physical_devices('GPU')))

Num GPUs Available: 2

print(tf.test.is_built_with_cuda())

True
```

I also found that if I run it in a Jupyter Notebook it works flawlessly. So, the obvious solution is just to do that, but it would be nice to understand why the GUI isn't working and if there's something I can help troubleshoot beyond just fixing my local problem, I would really like to help out. 

-Sincerely

**Comment by n-poulsen** [comment] 2024-04-02 14:34
Hi @VAmoroso13,

Most tensorflow versions (including all `tensorflow<=2.12`, which is required for DeepLabCut) are not compatible with the most recent versions of CUDA (see [this message](https://github.com/DeepLabCut/DeepLabCut/issues/2465#issuecomment-1861875446), where COLAB updating the default `CUDA` version lead to issues).

One easy solution, which is described in the thread linked above, would be to install an older version of `CUDA` in your `conda` environment. Could you try running (in your `DEEPLABCUT` conda environment):

```bash
conda activate DEEPLABCUT
conda install -c conda-forge cudnn==8.4.1.50 cudatoolkit==11.7.0
pip install "tensorflow<2.11" "tensorpack>=0.11" "tf_slim>=1.1.0"
```

These are `cudnn` and `cudatoolkit` versions that have worked well for other windows users with DeepLabCut.

From the [official `tensorflow`documentation](https://www.tensorflow.org/install/pip#windows-native), you could also try with the versions:

```bash
conda activate DEEPLABCUT
conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
# Anything above 2.10 is not supported on the GPU on Windows Native
python -m pip install "tensorflow<2.11"
# Verify the installation:
python -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

Let me know if using one of these versions solves your issue!

**Comment by VAmoroso13** [comment] 2024-04-02 20:01
I followed your instructions and the same problem is manifest. Same as in my first image, just the cuDNN version is 8.1.0.

I do find it odd that I can get it to work fully CUDA accelerated in a Jupyter Notebook, but not from the GUI. Why should this be?

**Comment by n-poulsen** [comment] 2024-04-04 12:44
@VAmoroso13 that's really curious - I can't really think of any reason it would work in a jupyter notebook but not the GUI. When calling `train_network` in your notebook, do you set the `gputouse` parameter?

**Comment by VAmoroso13** [comment] 2024-04-08 15:04
I do not call `gputouse`. Very repeatable behavior though with definite CUDA acceleration in Jupyter and nothing in the GUI. I just don't understand it.

**Comment by n-poulsen** [comment] 2024-04-12 16:23
@VAmoroso13 I don't understand it either... is the output of the `nvidia-smi` command you shared taken during video analysis? From the screenshot, it does seem that 13.7GB of the 16GB of GPU 0 is allocated, even though the utilization is 0.

And when you say the speed is very different between a notebook and the DeepLabCut GUI, could you time the entire operations (of the entire call of `analyze_videos`)? 

One more question: what do you mean by "first pass" of video analysis?

**Comment by VAmoroso13** [comment] 2024-04-12 16:44
Hello!

Several answers for you:

1) Yes, the `nvidia-smi` output was during Analysis. I too, noticed the memory use as well as the python 'compute' processes allocated. 
2) Saying "first" or "second" pass was silly of me and I had stopped using DLC for some time and forgotten what's under 'auto_track=true'.

"pass 1" = 'deeplabcut.analyze_videos'
"pass 2" = 'deeplabcut.convert_detections2tracklets'
"pass 3" = 'deeplabcut.stitch_tracklets'

3) The speed is drastically different for 'convert_detections2tracklets', I'm running something (in Jupyter) for a guy down the hall now, so can't run to completion, but to give you an idea -- it's as in the first posted image -- 6-10it/sec in GUI. When running in Jupyter or iPython, it's in the several thousands. 

Also, to deepen this bizarre mystery. If I run the GUI by running 'python -m deeplabcut', I don't get CUDA acceleration. If I run it explicitly in iPython which I tried yesterday (or Jupyter), it works. I just don't get it!

Again, I run things in command-line, but I was hoping to delegate to undergrads who your wonderful GUI would be better for. But, it's working in command-line, so.

**Comment by n-poulsen** [comment] 2024-04-15 13:39
The only pass where the GPU is used is "pass 1" - so if it's `deeplabcut.convert_detections2tracklets` and `deeplabcut.stitch_tracklets` that are much slower in the GUI, the issue does not come from the GPU not being used.

I'm not sure if there's much I can do, as you said it's very difficult to know where the issue is coming from, and I wasn't able to replicate it on my side. I'll close this issue for now.

**Closed as not planned by n-poulsen** 2024-04-15 13:39 UTC
Labels: Installation, more-data-requested-by-us, gpu
