### ISSUE TITLE
LossTensor is inf or nan while running my own dataset (Problem with data set)

### ISSUE THREAD

**Issue by cfanyyx** [DeepLabCut/DeepLabCut#62] opened 2018-09-19 04:15 UTC
**Hi, I am interested in your project very much and succeed running the demo.
But when I ran with my own dataset, I got error "LossTensor is inf or nan while running my own dataset".
Here is config info:**
Config:
{'all_joints': [[0],
                [1],
                [2],
                [3],
                [4],
                [5],
                [6],
                [7],
                [8],
                [9],
                [10],
                [11],
                [12],
                [13],
                [14],
                [15],
                [16],
                [17],
                [18],
                [19],
                [20]],
 'all_joints_names': ['hand0',
                      'hand1',
                      'hand2',
                      'hand3',
                      'hand4',
                      'hand5',
                      'hand6',
                      'hand7',
                      'hand8',
                      'hand9',
                      'hand10',
                      'hand11',
                      'hand12',
                      'hand13',
                      'hand14',
                      'hand15',
                      'hand16',
                      'hand17',
                      'hand18',
                      'hand19',
                      'hand20'],
 'batch_size': 1,
 'crop': False,
 'crop_pad': 0,
 'dataset': '../../UnaugmentedDataSet_handSep18/hand_openpose80shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 100,
 'fg_fraction': 0.25,
 'global_scale': 0.95,
 'init_weights': '../../pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1000,
 'mean_pixel': [123.68, 116.779, 103.939],
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 21,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'regularize': False,
 'save_iters': 5000,
 'scale_jitter_lo': 0.9,
 'scale_jitter_up': 1.1,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': './snapshot',
 'stride': 8.0,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}

**And I use 240 pics for training. After 100 iters, the error occurs:**
iteration: 0 loss: 0.0086 lr: 0.005
iteration: 100 loss: 0.8863 lr: 0.005
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: LossTensor is inf or nan : Tensor had NaN values
         [[Node: train_op/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="LossTensor is inf or nan", _device="/job:localhost/replica:0/task:0/device:CPU:0"](add)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../train.py", line 140, in <module>
    train()
  File "../../../train.py", line 119, in train
    feed_dict={learning_rate: current_lr})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: LossTensor is inf or nan : Tensor had NaN values
         [[Node: train_op/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="LossTensor is inf or nan", _device="/job:localhost/replica:0/task:0/device:CPU:0"](add)]]

Caused by op 'train_op/CheckNumerics', defined at:
  File "../../../train.py", line 140, in <module>
    train()
  File "../../../train.py", line 102, in train
    learning_rate, train_op = get_optimizer(total_loss, cfg)
  File "../../../train.py", line 71, in get_optimizer
    train_op = slim.learning.create_train_op(loss_op, optimizer)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 439, in create_train_op
    check_numerics=check_numerics)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/training/python/training/training.py", line 464, in create_train_op
    'LossTensor is inf or nan')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 498, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): LossTensor is inf or nan : Tensor had NaN values
         [[Node: train_op/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="LossTensor is inf or nan", _device="/job:localhost/replica:0/task:0/device:CPU:0"](add)]]

**I am wondering if anyone could help me with this problem?**

**Comment by AlexEMG** [comment] 2018-09-19 11:32
Perhaps change the learning rate schedule. Crank it down by quite a bit... 

'multi_step': [[0.005, 10000],
[0.02, 430000],
[0.002, 730000],
[0.001, 1030000]],


Perhaps from 0.005 to 0.00005 or so? Try if/when it blows up.

**Comment by cfanyyx** [comment] 2018-09-20 11:26
Thanks for your reply. But as so far, even if reducing the learning rate by 100 times (from 0.005 to 0.00005), it just increased the number of training iterations and delayed the time of reporting such error. It does‘t actually solve this problem.

**Comment by AlexEMG** [comment] 2018-09-20 18:01
That is strange - is there anything wrong about your labels & images? Did you check that there are any NANs in your labels (this should be done in Step4), that the labels fall outside the image (currently it does not check if they smaller than zero), etc...

**Comment by cfanyyx** [comment] 2018-09-21 06:47
The dataset and labels are all checked in step 3. There is nothing wrong about them. When I set lr to 0.00005, it could do 9k+ iters. Then I set lr to 0.000005, it has been running 21k+ iters. During the training process, lr has raised to 0.000002 after 10k iters. But the loss is no longer falling.

**Comment by AlexEMG** [comment] 2018-09-21 14:35
"The dataset and labels are all checked in step 3. "
Visually, but what if values are outside the image? Can you check them in the output file?
What is the size of your images?

This code has been used to train thousands of networks, odds are something is wrong with your labeled data set. This is a common issue, for many models, eg: https://github.com/tensorflow/models/issues/1881

**Closed as completed** 2018-09-23 13:50 UTC

**Comment by cfanyyx** [comment] 2018-09-25 02:53
I think it is a training problem. In my case, I reduced learning rate further so the iteration can rise to 80K. But the loss is no longer falling any more when it reached around 0.18. As the training progress continues, the loss will gradually increase until inf and throw **LossTensor is inf or nan** problem. @AlexEMG can you give me some advise about training? Do I need to change the dataset or batch size and retrain? And I also want to know if the size of pic influence training effect because the height and width of my training data are all around 100~200px? 

multi_step:
-- [0.000005, 10000]
-- [0.00002, 20000]
-- [0.000003, 50000]
-- [0.000002, 100000]
-- [0.000001, 500000]

**Comment by AlexEMG** [comment] 2018-09-27 16:02
Just for reference of others, @cfanyyx wrote me a pm stating that it was related to a wrong configuration of TensorFlow.

**Comment by bouracha** [comment] 2019-07-21 12:01
I have the same issue now. I have used used deeplabcut on a few datasets successfully but I am now getting this issue suddenly when I try to train a new dataset. The issue now also occurs when I got back to previous datasets and configurations that worked in the past so maybe I have changed something about my tensorflow configuration. Do you know what about the tensorflow configuration was problematic and how I might get this working again?

**Comment by AlexEMG** [comment] 2019-07-23 15:29
@bouracha  The learning rate could be to high, or there might be nans, or infs in the labeling data. However, given some projects could be trained earlier, it seems that your TensorFlow is broken. Perhaps try to re-install it?

**Comment by bouracha** [comment] 2019-07-24 14:02
There are blanks in the training data (where bodyparts were occluded) but as are there also in an earlier project where training worked. I now get the same error when I try to re-do training on exactly that old dataset. So it does look like it's a problem with tensorflow but I have tried reinstalling it so I'm not sure...

**Comment by bouracha** [comment] 2019-07-24 14:47
By the way, this is the error (it pauses on 'Starting training' for about 30 seconds):

```
Starting training....
2019-07-24 15:37:41.860576: E tensorflow/core/kernels/check_numerics_op.cc:189] abnormal_detected_host @0x200a10f00 = {1, 0} LossTensor is inf or nan
Traceback (most recent call last):
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: LossTensor is inf or nan : Tensor had NaN values
[[{{node train_op/CheckNumerics}}]]
[[train_op/control_dependency/_621]]
  (1) Invalid argument: LossTensor is inf or nan : Tensor had NaN values
[[{{node train_op/CheckNumerics}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pn/env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 97, in train_network
    raise e
  File "/home/pn/env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 95, in train_network
    train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep) #pass on path and file name for pose_cfg.yaml!
  File "/home/pn/env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 158, in train
    feed_dict={learning_rate: current_lr})
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: LossTensor is inf or nan : Tensor had NaN values
[[node train_op/CheckNumerics (defined at /home/pn/env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/train.py:90) ]]
[[train_op/control_dependency/_621]]
  (1) Invalid argument: LossTensor is inf or nan : Tensor had NaN values
[[node train_op/CheckNumerics (defined at /home/pn/env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/train.py:90) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node train_op/CheckNumerics:
 add (defined at /home/pn/env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/nnet/pose_net.py:132)

Input Source operations connected to node train_op/CheckNumerics:
 add (defined at /home/pn/env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/nnet/pose_net.py:132)

Original stack trace for 'train_op/CheckNumerics':
  File "<stdin>", line 1, in <module>
  File "/home/pn/env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 95, in train_network
    train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep) #pass on path and file name for pose_cfg.yaml!
  File "/home/pn/env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 119, in train
    learning_rate, train_op = get_optimizer(total_loss, cfg)
  File "/home/pn/env/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 90, in get_optimizer
    train_op = slim.learning.create_train_op(loss_op, optimizer)
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 442, in create_train_op
    check_numerics=check_numerics)
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/contrib/training/python/training/training.py", line 467, in create_train_op
    'LossTensor is inf or nan')
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1010, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/pn/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by MMathisLab** [comment] 2019-07-24 23:22
^ can you double check your collected_data file has no NaNs?

**Comment by bouracha** [comment] 2019-07-25 08:41
Yes, sorry I wasn't clear. It does have blanks which are nans at least when I open them up in pandas but these correspond to bodyparts that were not labelled for a given frame. The issue is that I seem to also have them in older datasets for which training did work and for which I have not altered the dataset.

If the problem is these nans what could I be doing wrong to create them? What should be in the train set where bodyparts are occluded?

**Comment by bouracha** [comment] 2019-07-25 08:48
For example, the first row of this training data corresponds to this image. I have not labelled the left hand as it can't be seen and as a result it's NaN in the training set.

![Screenshot from 2019-07-25 09-45-51](https://user-images.githubusercontent.com/17855974/61860041-2e497d00-aec1-11e9-9be7-f253e79f5d81.png)

**Comment by MMathisLab** [comment] 2019-07-25 12:44
They are blank when you label in our GUIs, not nans; nans would have never run on any version of tensorflow...

**Comment by bouracha** [comment] 2019-07-25 13:22
That is strange, I've started several new projects and it keeps creating them like this. I'll try once again but I presume a hacky solution is to just replace these nans with empty strings?

**Comment by bouracha** [comment] 2019-07-25 13:35
They are only nans when I read them into pandas. If I open them in libre office (see screenshot) They are blanks.... What are these blanks suppose to be?

![Screenshot from 2019-07-25 14-30-49](https://user-images.githubusercontent.com/17855974/61878645-48975100-aee9-11e9-8292-9f18152977c3.png)

**Comment by bouracha** [comment] 2019-07-25 13:42
and also in text editor..

![Screenshot from 2019-07-25 14-41-27](https://user-images.githubusercontent.com/17855974/61879126-5c8f8280-aeea-11e9-9a37-295938955633.png)

**Comment by MMathisLab** [comment] 2019-07-25 14:21
They should be blanks.

**Comment by bouracha** [comment] 2019-07-25 14:44
They are blanks here though..

**Comment by MMathisLab** [comment] 2019-07-25 14:58
Idk what happened to your h5 files. I would check the csvs, be sure all blank, then use the function convertcsvtoh5 to fix the h5s.

**Comment by bouracha** [comment] 2019-07-25 15:42
Wooooo, yes that worked! Thank you! Still no idea why my h5 files were consistently being corrupted however!

**Comment by MMathisLab** [comment] 2019-07-25 15:57
Yeah idk, maybe opening/saving them changed something; glad it’s resolved

**Comment by bouracha** [comment] 2019-07-25 16:20
Yes, thanks for your help. It does sometime crash after a few thousand iterations so maybe the learning rate is also a problem. Though this seems to be set and change automatically and I don't see in the documentation how to change this. What was it that you recommended to do in this case- how do I change the learning rate?

**Comment by bouracha** [comment] 2019-07-25 16:24
Thanks, for the help.

**Comment by tzeriver** [comment] 2021-08-18 18:37
I had this same error today. Reinstall tensorflow solves the issue.
