### ISSUE TITLE
Memory error during kmeans clustering in 'extract_frames()': "exit code -1073741819 (0xC0000005)"

### ISSUE THREAD

**Issue by jkbhagatio** [DeepLabCut/DeepLabCut#1826] opened 2022-05-09 09:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When running `extract_frames()` on a video with ~80000 frames, kmeans clustering crashed the python console with the following error exit code: -1073741819 (0xC0000005)

I would guess this is a low-level memory r/w error. Naively I'm guessing there could be multiple solutions to this, from stopping the process on dlc's side to return control to the python console with a message saying something like "too many frames for kmean clustering", or doing something like gpu-enabled clustering?

### Operating System

Windows 10

### DeepLabCut version

2.2.1

### DeepLabCut mode

single animal

### Device type

GPU RTX 3080

### Steps To Reproduce

Running `extract_frames()` on a video file with >80000 frames.

### Relevant log output

```
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 180.0  seconds to 3420.0  seconds.
Extracting and downsampling... 81000  frames from the video.
81000it [32:22, 41.71it/s]
Kmeans clustering ... (this might take a while)

Process finished with exit code -1073741819 (0xC0000005)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment] 2022-05-11 07:26
There are multiple potiential causes. From not running the terminal as admin, corrupted file, bad installation of the env to RAM issues. 
On more than one occasion I've run clustering on videos with 120k-180k frames by accident and never had this issue even on my 16GB RAM laptop so I wouldn't think this is the cause (also then I'd expect some sort of oom and not Windows erroring out)

**Comment by jeylau** [comment] 2022-05-16 09:46
@jkbhagatio, I concur with what Konrad said above. Out of curiosity, I tried with a 3D array occupying 12gb of memory (1M frames downsampled to a width of 40 pixels), and MiniBatchKMeans had no problem fitting the data in ~25 s.
One thing you could try is to run `extract_frames` with a lower `cluster_resizewidth` (e.g., you could try with 10 pixels) and a higher `cluster_step`(e.g., 5–10) to reduce the memory footprint. If it still crashes, try to uninstall and reinstall scipy and scikit-learn. I hope this helps!

**Comment by jkbhagatio** [comment] 2022-05-20 18:34
Hm ok, so I'm confident none of these are issues:

> There are multiple potiential causes. From not running the terminal as admin, corrupted file, bad installation of the env to RAM issues.

And yes a lower `cluster_resizewidth` and higher `cluster_step` does help, but like you say probably just because this reduces the memory size of the array that kmeans runs on.

I believe the memory size of the array in my case was 40 * 30 * 80000 * 8 ~ 800 mb (1440 x 1080 pixels reduced to 40x30, 80000 frames, and 8 bytes per element) . Just from cursory messing around, it worked fine with the same settings but cluster_step at 10, so a 10x reduction in size I guess to ~ 80 mb. 

> Out of curiosity, I tried with a 3D array occupying 12gb of memory (1M frames downsampled to a width of 40 pixels), and MiniBatchKMeans had no problem fitting the data in ~25 s.

This is interesting - a good sanity check. Could you share with me your hardware and software specs and point me to the KMeans function you used here? Was it a call to the exact same function used in `extract_frames()` ?

Thanks!

**Comment by jeylau** [comment] 2022-05-30 08:32
Hey @jkbhagatio, it's a Ubuntu workstation w/ 64GB of RAM, and 20 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz processors. I had simply created the large array and fed it to `MiniBatchKMeans`, done in DeepLabCut [here](https://github.com/DeepLabCut/DeepLabCut/blob/7df1753943538f6b9ccdac1df61d58b74e1fa6f2/deeplabcut/utils/frameselectiontools.py#L389-L392)

**Comment by jkbhagatio** [comment] 2022-05-31 18:50
> also then I'd expect some sort of oom and not Windows erroring out

@KonradDanielewski So to be clear, the error I get is a memory error: `Process finished with exit code -1073741819 (0xC0000005)`
https://social.microsoft.com/Forums/en-US/431265d6-823e-4671-ae31-6e2b7e40170f/exit-code-0xc0000005?forum=windowshpcmpi

The error does occur during `kmeans.fit(data)` with for me an array > 700 mb. @cawa-93 have you had the same issue?

@jeylau what version of sklearn did you have when you ran it? Mine was 1.0.2

I'm running a Windows with a ryzen 9 5950X - I could try compiling sklearn from source for this and trying again, may be performance benefits anyway due to default intel mkl crippling of instruction sets for amd cpus?

**Comment by jeylau** [comment] 2022-06-02 07:23
I ran it with sklearn 1.0, and have no problem with 1.0.2 either. I'm not convinced it is worth installing sklearn from source just for frame extraction. Since you seem limited by hardware anyway, I'd just tune `cluster_step` and `cluster_resizewidth` as it worked earlier, and continue with your project. Note that you could also use `algo=uniform` to extract frames uniformly: there is no clustering involved so memory usage is limited, though it is not ideal if the behavior of interest is sparse.

**Comment by jkbhagatio** [comment] 2022-06-05 22:33
>Since you seem limited by hardware anyway

This shouldn't be the case - it seems to be a software issue: a ryzen 9 5950X should have no issues running kmeans on ~1 gig of data.

Yeah my project is fine, just interested in the root cause of this error. Anyway since it's an sklearn issue and I want to optimize sklearn on my machine anyway I will install from source and see how it goes - feel free to close this, I'll provide an update comment anyway if I get to the root cause.

**Comment by jeylau** [comment] 2022-06-29 09:12
I'll close the issue, but feel free to reopen it or give us some feedback if you figure out what the root cause is!

**Closed as completed by jeylau** 2022-06-29 09:12 UTC
