### ISSUE TITLE
Extract_outlier_frames and refine_labels not working

### ISSUE THREAD

**Issue by isabelperezf** [DeepLabCut/DeepLabCut#1789] opened 2022-04-22 15:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

We (@auesro and me) are using maDLC for single animal videos and we found two, maybe related, problems after running `analyze_videos` :

1. The function `extract_outlier_frames` says: 
```
Analyzing all the videos in the directory...
No unfiltered data file found in /content/drive/Shareddrives/Computational_Neuro_IP-AER/Test_maDLC_multi_2/singleanimal-IsabelP-2022-03-24/videos for video 8-2-2021_Chloroquine_19 and scorer DLC_dlcrnetms5_singleanimalMar24shuffle1_100000 and ellipse tracker.
It seems the video has not been analyzed yet, or the video is not found! You can only refine the labels after the a video is analyzed. Please run 'analyze_video' first. Or, please double check your video file path
```
2. After running the function `find_outliers_in_raw_data` (recently fixed by @jeylau #1778), the function `refine_labels` opens the GUI but it does not find any frames to correct (apparently the GUI is looking for a `machinelabels-iter0.h5` file which is not in the folder).

Any ideas?

### Operating System

Microsoft Windows 10 Pro and COLAB

### DeepLabCut version

DLC 2.2.0.1

### DeepLabCut mode

multi animal

### Device type

NVIDIA Quadro P2000

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment] 2022-04-22 16:17
@isabelperezf to use the refine labels GUI one needs to first run:
(1) analyze_videos
(2)  extract_outlier_frames 

Your error says: " It seems the video has not been analyzed yet, or the video is not found! You can only refine the labels after the a video is analyzed. Please run 'analyze_video' first. Or, please double check your video file path"

can you check if you have a .h5 file for your video in the folder? 

The path you are taking with 2. --> "After running the function find_outliers_in_raw_data (recently fixed by @jeylau https://github.com/DeepLabCut/DeepLabCut/issues/1778), the function refine_labels opens the GUI but it does not find any frames to correct (apparently the GUI is looking for a machinelabels-iter0.h5 file which is not in the folder)."

Does not use the refinement GUI, you would need to open the regular labeling GUI; the unmarked frames will appear there.

**Comment by auesro** [comment] 2022-04-22 16:30
Hi @MMathisLab 

We of course first ran `analyze_videos`. But we got a _full.pickle and a _meta.pickle files, no h5 files whatsoever.

**Comment by MMathisLab** [comment] 2022-04-22 17:05
@auesro for maDLC is there is no pickle unless you set auto_track=True (quick guide here: https://deeplabcut.github.io/DeepLabCut/docs/tutorial.html)
- re: "find_outliers_in_raw_data" are the extracted frames in the labeled-data folder? Openning using normal label_frames GUI?

**Comment by auesro** [comment] 2022-04-22 17:20
This is the command we used in COLAB:
`deeplabcut.analyze_videos(path_config_file,['/content/drive/Shareddrives/Computational_Neuro_IP-AER/Test_maDLC_multi_2/singleanimal-IsabelP-2022-03-24/videos/8-2-2021_Chloroquine_5.mp4'], shuffle=shuffle, videotype=VideoType, save_as_csv=True, robust_nframes=True, allow_growth=True, auto_track=False)`

>     * re: "find_outliers_in_raw_data" are the extracted frames in the labeled-data folder? Openning using normal label_frames GUI?
Yes, they are there and we can see them (and label) using `label_frames`. but of course, we would like to be able to use `refine_labels`.

**Comment by MMathisLab** [comment] 2022-04-22 18:23
>> Yes, they are there and we can see them (and label) using label_frames. 

okay great, that is the expected behavior actually :) 

If you want to use refine labels GUI, you would need to set `auto_track=True`, then you get the `.h5`. 

From there you can  (1) use the tracklet refinement GUI, set "0" to gap to fill (then everything will be shown) and you can move points and when you are done click MERGE:
<img width="1304" alt="Screen Shot 2022-04-22 at 7 13 38 PM" src="https://user-images.githubusercontent.com/28102185/164772496-67b5828e-bb34-4ee1-a130-903f58060400.png">

or (2) run extract outlier frames, then launch refinement GUI.

**Closed as completed by MMathisLab** 2022-04-22 18:23 UTC
Labels: howtousedlc, maDLC

**Comment by auesro** [comment] 2022-04-23 15:30
Dear Mackenzie,

Thanks for your help. If I understood correctly, what you are saying is that we should:
1. `analyze_video` with auto_track=True
OR
2. `analyze_video` with auto_track=False + `convert_detections2tracklets` + `stitch_tracklets`
and then
3. `extract_outlier_frames` if desired/necessary.

If thats correct, then I think you should consider changing the message output of `analyze_video` because right after it finishes goes with: 
```
The videos are analyzed. Time to assemble animals and track 'em... 
 Call 'create_video_with_all_detections' to check multi-animal detection quality before tracking.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
```
Which I find a bit misleading if you ran with auto_track=False. This was actually what happened to us, we thought we could go from `analyze_video` to `extract_outlier_frames`.

Cheers,

A

**Comment by MMathisLab** [comment] 2022-04-23 16:29
>>  Call 'create_video_with_all_detections' to check multi-animal detection quality before tracking.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.

That is true - this is the workflow for single animal DLC, you go from analyze_videos to extract, but indeed not for maDLC; we changed the docs, but agree we could change `You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.` for maDLC cc @jeylau - what do you think?

**Comment by auesro** [comment] 2022-04-23 16:41
> okay great, that is the expected behavior actually :)

Actually, I think it would be great if the expected behavior would be to obtain those frames TOGETHER with their predicted positions (equivalent to extract_outlier_frames, after all we are also passing a p_cutoff here) making it compatible with refine_labels GUI. Otherwise, the advantage of extracting these outliers in raw data compared to extracting them after track assembly is rather small, right? It is very informative to visually see where the network placed its predictions. 
Just thinking out loud.
