### ISSUE TITLE
 wxAssertionError: C++ assertion

### ISSUE THREAD

**Issue by 0tist** [DeepLabCut/DeepLabCut#1079] opened 2021-01-13 15:43 UTC
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**operating system - 20.04 LTS and DeepLabCut version - 2.1.9 with pip installed virtual environment**

Please complete the following information about your system:

OS: Ubuntu 20.04
DeepLabCut Version: 2.1.9
Anaconda env used:

**Describe the problem**

I'm trying to use label frames with deeplabcut.label_frames, and %gui wx. got the error as shown below

wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at /tmp/pip-install-e31jp07k/wxpython/ext/wxWidgets/src/common/sizer.cpp(2164) in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers

Please place code inside this:

<details><summary>import deeplabcut as dlc</summary><p>

[wxAssertionError                          Traceback (most recent call last)
<ipython-input-7-35877b792a8c> in <module>
      1 get_ipython().run_line_magic('gui', 'wx')
----> 2 dlc.label_frames(path_config_file)

~/.local/lib/python3.8/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in label_frames(config, multiple_individualsGUI, imtypes)
    429         from deeplabcut.generate_training_dataset import labeling_toolbox
    430 
--> 431         labeling_toolbox.show(config, imtypes=imtypes)
    432 
    433     os.chdir(startpath)

~/.local/lib/python3.8/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py in show(config, imtypes)
   1009 def show(config, imtypes=["*.png"]):
   1010     app = wx.App()
-> 1011     frame = MainFrame(None, config, imtypes).Show()
   1012     app.MainLoop()
   1013 

~/.local/lib/python3.8/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py in __init__(self, parent, config, imtypes)
    257         widgetsizer.AddStretchSpacer(15)
    258         self.quit = wx.Button(self.widget_panel, id=wx.ID_ANY, label="Quit")
--> 259         widgetsizer.Add(self.quit, 1, wx.ALL | wx.ALIGN_RIGHT, 15)
    260         self.quit.Bind(wx.EVT_BUTTON, self.quitButton)
    261 

wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at /tmp/pip-install-e31jp07k/wxpython/ext/wxWidgets/src/common/sizer.cpp(2164) in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
]

</p></details>

**How to Reproduce the problem**
1. define task
2. define experimenter
3. define video_folder
4. extract frames
5. label frames with wxPython

**Comment by jeylau** [comment] 2021-01-15 08:38
Duplicate of #926

The solution is to `pip install -U wxPython==4.0.7.post2`

**Closed as completed by jeylau** 2021-01-15 08:38 UTC
