### ISSUE TITLE
Many errors thrown when running testscript.py immediately after installation, output not matching tutorial

### ISSUE THREAD

**Issue by pranavgurusankar** [DeepLabCut/DeepLabCut#1428] opened 2021-07-20 23:30 UTC
** System Information **
OS: MacOS 10.15.17
DeepLabCut Version: Latest version, downloaded today (20 July 2021)
Anaconda env used: DEEPLABCUT (from DEEPLABCUT.yaml)

**Problem Description**
Direct reference to my recent response to #1413 (reposting as a separate issue because #1413 was closed). When I run testscript.py, as described in the tutorial video (https://www.youtube.com/watch?v=IOWtKn3l33s) immediately after installing DLC and then activating the conda environment, the execution of the program seems to throw multiple exceptions and errors which do not appear in the video. A lot of the data and messages about training the network also do not appear for me. Not sure why. 

**Screenshots**
![Screenshot 2021-07-20 at 4 23 15 PM](https://user-images.githubusercontent.com/37655744/126407757-66c9a5bc-47a6-401c-9a3e-ebc600cf2b54.png)
![Screenshot 2021-07-20 at 4 22 40 PM](https://user-images.githubusercontent.com/37655744/126407759-660d7766-d3ae-4219-90fe-849bd01ca57b.png)

**Additional context**
Also had some interesting, potential "error", messages thrown during the installation of the conda environment from the .yaml file (i.e. when executing conda env create -f DEEPLABCUT.yaml). Not sure if this is relevant. Screenshot below:

![Screenshot 2021-07-20 at 4 06 03 PM](https://user-images.githubusercontent.com/37655744/126407837-08213651-01e5-4dac-a6db-4233d746d035.png)

**Comment by backyardbiomech** [comment] 2021-07-21 12:36
Duplicate of #1426 . This is a mismatch between the installed version of DLC and the testcript version.

**Comment by pranavgurusankar** [comment] 2021-07-21 18:52
Noted. How do I resolve the issue? I noticed on #1426 that the core issue
was not using the latest version of DLC. But I downloaded DLC from the git
repo yesterday, so I assume it is the latest build. Given that, why does
the issue still persist?

**Comment by MMathisLab** [comment] 2021-07-21 20:54
@pranavgurusankar please tell us what the output of this is?: 
```
import deeplabcut
deeplabcut.__file__
```
as @backyardbiomech suggests, it is most likely you are not using the latest from github; please see here for the usage guide for how to be sure you have installed from github (i.e., just downloading is not enough): https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#how-to-use-the-latest-updates-directly-from-github

(also side note, emailing me directly won't make our help any faster - we are a group of developers and users that support the community as best we can, but the code is open source, free, and without any promises of such support  ;)

**Comment by jeylau** [comment] 2021-07-26 07:56
@pranavgurusankar, please downgrade pandas with `pip install pandas<1.3`. The newest pandas version complains about a little something that we only fixed recently https://github.com/DeepLabCut/DeepLabCut/commit/5afe853a2fbfcf74674b635a8966e5ea94de3716

**Closed as completed by jeylau** 2021-07-26 07:56 UTC
Labels: Installation, howtousedlc
