### ISSUE TITLE
occasional 'failed to load module error'

### ISSUE THREAD

**Issue by ashwin-miriyala** [DeepLabCut/DeepLabCut#1094] opened 2021-01-27 11:12 UTC
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). 
Please fill out the template completely, including the full "TRACEBACK" and input code that you ran to hit this error.

I occasionally find that when I run deeplabcut.extract_frames or deeplabcut.label_frames, I get some 'failed to load module' errors.

Please provide the minimal required code to reproduce the error and the full output (please edit ONLY the section below that says `PLACE YOUR CODE HERE!!! `.

**Desktop (please complete the following information about your system):**
- OS: [Linux Ubuntu 18.04.5 LTS]
 - DeepLabCut Version : 2.1.10
 - DeepLabCut mode : single animal tracking
 - -iPython

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. the input code you used -
deeplabcut.extract_frames(configPath,mode='automatic',algo='kmeans',crop='GUI')
deeplabcut.label_frames(configPath)

4. See error:

<details><summary>TRACEBACK</summary><p>

```python


Gtk-Message: 10:06:05.771: Failed to load module "overlay-scrollbar"
Gtk-Message: 10:06:05.776: Failed to load module "atk-bridge"
Gtk-Message: 10:06:05.783: Failed to load module "canberra-gtk-module"


```
</p></details>

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (but please post the code output above, not images of code!)

**Additional context**
When this happens after executing deeplabcut.extract_frames, this prevents me from exiting the GUI window using the 'crop' button.  However, this doesn't happen every time I run this code .. sometimes the errors don't appear and I can continue as usual. 

A similar issue happens when I run label_frames
deeplabcut.label_frames(configPath)
Where in addition to the module load errors, I get a long list of repeating critical and warning errors:
(ipython:24632): GLib-GObject-CRITICAL **: 10:07:15.883: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
(ipython:24632): Gtk-WARNING **: 10:07:15.883: Error loading theme icon 'image-missing' for stock: Failed to load icon

**Comment by MMathisLab** [comment] 2021-01-27 15:20
I'm not sure; if its not happening normally, it's quite hard for us to debug; looking at it, you might just have a different version of wxPython than we recommend?

**Comment by jeylau** [comment] 2021-02-05 09:37
Duplicate of #1012.

**Closed as completed by jeylau** 2021-02-05 09:37 UTC
