### ISSUE TITLE
Inconsistent individual identity

### ISSUE THREAD

**Issue by DavidAlWolf** [DeepLabCut/DeepLabCut#762] opened 2020-06-21 10:42 UTC
Hi, 
first of all thank you for the great software, especially the multi-animal extension. I have experienced a weird issue running the latest release 2.2b6. This bug is not reproducable in 2.2b5 for me.
Thanks in advance for the help and all the best,
David

**Describe the bug**

After labelling and saving frames in 2.2b6 the marker identities are mixed up, i.e. when I running "Check Labels Individual" markers aren't where they supposed to be and when re-opening the "label frames" GUI, also the markers aren't where I placed them before (see steps to reproduce and screenshots) 

**Desktop (please complete the following information about your system):**
 - OS: Windows10
- DeepLabCut Version: 2.2b6

**To Reproduce**
Steps to reproduce the behavior, i.e.:
In the GUI:
1. "Label Frames" (screenshot 1)
2. "Save"
3. "Quit"
4. "Check Labels Individuals" (screenshot 2)
5. "Label Frames" and load same video and frame as before (screenshot 3)

**Expected behavior**
Keep markers in correct position.

**Screenshots**
Screenshot 1:
![screenshot1](https://user-images.githubusercontent.com/51506428/85222544-41f4b080-b3bc-11ea-89f6-6396b1bb743b.png)

Screenshot 2:
![screenshot2](https://user-images.githubusercontent.com/51506428/85222548-4d47dc00-b3bc-11ea-82d0-e6fac7599d67.png)

Screenshot 3:
![screenshot3](https://user-images.githubusercontent.com/51506428/85222549-53d65380-b3bc-11ea-8428-a2be5043423d.png)

**Comment by MMathisLab** [comment] 2020-06-21 16:18
can you confirm that in screenshot 2, you don't have any "uniquebodyparts" connected in the "skeleton" to ANY multanimalbodypart? thanks!

also, can you report:
```python
import matplotlib 
matplotlib.__version__

import pandas
pandas.__version__

import wxPython
wx.__version__
```

**Comment by DavidAlWolf** [comment] 2020-06-21 19:25
Yes I can confirm that. The Skeleton was configured using the Skeleton-builder from the GUI. I also attatched the config.yaml below.

[config.txt](https://github.com/DeepLabCut/DeepLabCut/files/4810124/config.txt)

I freshly installed in a new Conda Environment using the DLC-GPU file from your Website and 'pip install deeplabcut==2.2b6'. These are the current versions:
![packages](https://user-images.githubusercontent.com/51506428/85233247-2f529980-b405-11ea-960b-1a798ed55f12.PNG)

One more thing I noticed: When labelling in Version 2.2b5 with the exact same Settings and configurations I don't run into this Problem and the columns of the resulting "CollectedData" hdf-files look different:

This is how they look like in 2.2b6: (there are a few lines cut off but it continues with 'juvenile' to the end)
![b6_columns](https://user-images.githubusercontent.com/51506428/85233282-75a7f880-b405-11ea-90ab-3c776c630761.PNG)

This is how they look like in 2.2b5 (here the uniquebodyparts come at the end as "single")
![b5_columns](https://user-images.githubusercontent.com/51506428/85233283-7771bc00-b405-11ea-815b-d0c1bc3c0e49.PNG)

**Comment by neurologic** [comment] 2020-06-22 11:33
Hello,
I am also having this same problem.
I am also running this on:
<ul><li>OS: Windows10</li>
<li>DeepLabCut Version: 2.2b6</li>
<li>Environment: DLC-GPU.yaml</li>
</ul>

WORKFLOW TO REPRODUCE:
1) I used the GUI to do all steps leading up to the check_labels.
 *note: if it matters, for ```extract frames``` I need to select ```want to use OpenCV?``` to ```no``` because it fails if I do ```yes``` (I suppose I probably don't have OpenCV installed but have not got around to that yet since the ```no``` option worked -- ie. let me proceed).

2) ```Label Frames``` followed by Save/Quit after doing the labeling.
3) ```Check Labels``` (and ```check individual labels``` resulted in same misbehavior)
4) Look at the resulting images generated: The labels were very far off from what I had done.
In all cases I have seen so far, the incorrect images are incorrect in the following way: the skeletons were the correct shape/connection, they were just not located in the correct part of the image. Almost as if the labels were being associated with the wrong images. (*note: I did see a couple that ended up correctly labelled, but the majority were incorrect*)
5) However, unlike @DavidAIWolf, when I return to the ```Label Frames``` function in the GUI the labels on these images are still in the location that I had put them before checking the labels

I also have:
![image](https://user-images.githubusercontent.com/4777333/85280470-31911400-b456-11ea-82e4-b2efbef3d158.png)
*note: ```import wxPython``` was not recognized, only ```import wx```*

Here is the config file as .txt confirming uniquebody parts are not connected to multianimal (I don't have any unique)(I just set extract frame number variable to '3' to start debugging this):
[config.txt](https://github.com/DeepLabCut/DeepLabCut/files/4812828/config.txt)

**Labeling:**
(followed by SAVE/QUIT after labeling)
![image](https://user-images.githubusercontent.com/4777333/85282239-66eb3100-b459-11ea-91cd-d130f03ce4c5.png)
![image](https://user-images.githubusercontent.com/4777333/85282367-9d28b080-b459-11ea-8b3a-458d73bb28c0.png)

**Result of ```Check Labels``` (run from GUI):**
![image](https://user-images.githubusercontent.com/4777333/85282637-145e4480-b45a-11ea-8e87-5d7c002dd92e.png)
![image](https://user-images.githubusercontent.com/4777333/85282676-2344f700-b45a-11ea-9c86-43bfb0a0475b.png)

**Return to GUI and go back to ```Label Frames```:**
The labels actually still are in the correct location according to the label frames part of the GUI. Even though check labels was incorrectly matched between skeleton and image.
![image](https://user-images.githubusercontent.com/4777333/85283389-49b76200-b45b-11ea-8ef2-76f57c1ac88d.png)

**Comment by jeylau** [comment] 2020-06-22 11:48
@DavidAlWolf @neurologic, thank you both for the thorough reports! I expect to push a fix this afternoon, please wait a little longer 😄

**Comment by neurologic** [comment] 2020-06-22 11:51
Thanks, @jeylau ! I look forward to it :)
Just wanted to check if you saw my last edit (I had gone back to ```Label Frames``` after posting my comment and saw that, unlike DavidAIWolf, my labels were actually still in the correct location that I had placed them on every image. Even though the ```Check Labels``` had them wrong.

**Comment by jeylau** [comment] 2020-06-22 14:22
I saw it @neurologic :) I am not sure why though. The issue should be solved in #764, please let me know if that works!

**Comment by neurologic** [comment] 2020-06-22 15:45
Awesome, @jeylau !
Would you recommend that we wait until this is merged with master to try it or can we clone this fix branch and install to try it before then?

**Comment by jeylau** [comment] 2020-06-22 17:27
I'd wait for the merge, this will be done today :)

**Comment by MMathisLab** [comment] 2020-06-22 19:41
[ I just came to say, sweet fish videos!]

**Closed as completed** 2020-06-22 20:19 UTC
Labels: bug

**Comment by neurologic** [comment] 2020-06-22 20:55
;) @MMathisLab thanks! They are pulse-type electric fish. I am stoked MultiAnimal functionality has been developed/posted just in time for me to start moving to a new teaching/lab position this coming winter where I had plans for multianimal needs! This will be my first foray into behavior video data and tracking.

[I know the lighting is not ideal yet as seen in the screenshots. These are just my quick iPhone videos to get started on the software, etc... "real" lab set up is under development :) ]

**Comment by DavidAlWolf** [comment] 2020-06-24 12:20
Thanks for the super quick fix! :)
