### ISSUE TITLE
cannot create video with skeleton

### ISSUE THREAD

**Issue by WeissShahaf** [DeepLabCut/DeepLabCut#1698] opened 2022-02-22 11:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

deeplabcut.create_labeled_video(config_path,videos,shuffle = 3,filtered=True) works
but when i try:
deeplabcut.create_labeled_video(config_path,videos,shuffle = 3,filtered=True, draw_skeleton = True)

it crashes

### Operating System

operating system: WIN10

### DeepLabCut version

dlc version '2.2.0.6'

### DeepLabCut mode

single animal

### Device type

gpu: A6000

### Steps To Reproduce

run:
deeplabcut.create_labeled_video(config_path,videos,shuffle = 3,filtered=True, draw_skeleton = True)
error:
Starting to process video: C:\Users\superuser\Videos\Gl108420210601_short.mp4
Loading C:\Users\superuser\Videos\Gl108420210601_short.mp4 and data.
Labeled video already created. Skipping...

In [8]: deeplabcut.create_labeled_video(
   ...:     config_path, videos, shuffle=3, filtered=True, draw_skeleton=True
   ...: )
Starting to process video: C:\Users\superuser\Videos\Gl108420210601_short.mp4
Loading C:\Users\superuser\Videos\Gl108420210601_short.mp4 and data.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 671, in proc_video
    CreateVideo(
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 83, in CreateVideo
    bpts2connect = get_segment_indices(bodyparts2connect, all_bpts)
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 43, in get_segment_indices
    for bpt1, bpt2 in bodyparts2connect:
ValueError: too many values to unpack (expected 2)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-ba181324150c>", line 1, in <module>
    deeplabcut.create_labeled_video(
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 518, in create_labeled_video
    pool.map(func, Videos)
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC202202\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\terminal\ipapp.py", line 316, in start
    self.shell.mainloop()
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\terminal\interactiveshell.py", line 611, in mainloop
    self.interact()
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\terminal\interactiveshell.py", line 604, in interact
    self.run_cell(code, store_history=True)
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "C:\ProgramData\Anaconda3\envs\DLC202202\lib\site-packages\IPython\core\ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

If you suspect this is an IPython 8.0.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment] 2022-02-23 14:12
This looks like a problem with how the `skeleton` section of your `config.yaml` is formatted. Please copy and paste that here.

**Comment by jeylau** [comment] 2022-03-01 08:42
@WeissShahaf, could you fix the skeleton definition in your config.yaml file?

**Comment by jeylau** [comment] 2022-03-02 10:22
Closing as it is a typo in the config.yaml.

Also, duplicate of #1527 #1452

**Closed as completed by jeylau** 2022-03-02 10:22 UTC

**Comment by WeissShahaf** [comment] 2022-03-03 10:23
i did manage to fix it in the config.yaml.
it was indeed a typo. thanks
