### ISSUE TITLE
As we say in docs, you cannot run calibrate=True until you remove any bad pairs from the folder???

### ISSUE THREAD

**Issue by Dvirbs** [DeepLabCut/DeepLabCut#948] opened 2020-10-07 12:00 UTC
Describe the bug:
Problem in the iterative process of the camera calibration.
I use calibrate=False several times and remove any bad pairs from the folder. Then run calibrate=True.
But I get this error:
```

Corners not found for the image camera-1-01981.jpg
Corners not found for the image camera-1-02001.jpg
Corners not found for the image camera-1-02021.jpg
...
...
...
Corners not found for the image camera-2-06521.jpg
Corners not found for the image camera-2-06541.jpg
Corners not found for the image camera-2-06561.jpg
Saving intrinsic camera calibration matrices for camera-1 as a pickle file in C:\Users\Owner\Desktop\Dvir\DvirDLC\projects\3DProject_try#5-Dvir-2020-10-07-3d\camera_matrix
Mean re-projection error for camera-1 images: 0.023 pixels 
Saving intrinsic camera calibration matrices for camera-2 as a pickle file in C:\Users\Owner\Desktop\Dvir\DvirDLC\projects\3DProject_try#5-Dvir-2020-10-07-3d\camera_matrix
Mean re-projection error for camera-2 images: 0.038 pixels 
Computing stereo calibration for 
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-16-8e9d0546cf06> in <module>
----> 1 deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=6, calibrate=True, alpha=0.9)

~\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_3d\camera_calibration.py in calibrate_cameras(config, cbrow, cbcol, calibrate, alpha)
    156         for pair in camera_pair:
    157             print("Computing stereo calibration for " %pair)
--> 158             retval, cameraMatrix1, distCoeffs1, cameraMatrix2, distCoeffs2, R, T, E, F = cv2.stereoCalibrate(objpoints[pair[0]],imgpoints[pair[0]],imgpoints[pair[1]],dist_pickle[pair[0]]['mtx'],dist_pickle[pair[0]]['dist'], dist_pickle[pair[1]]['mtx'], dist_pickle[pair[1]]['dist'],(h,  w),flags = cv2.CALIB_FIX_INTRINSIC)
    159 
    160             # Stereo Rectification

error: OpenCV(3.4.7) C:\projects\opencv-python\opencv\modules\calib3d\src\calibration.cpp:3120: error: (-215:Assertion failed) nimages > 0 && nimages == (int)imagePoints1.total() && (!imgPtMat2 || nimages == (int)imagePoints2.total()) in function 'cv::collectCalibrationData'
```

To Reproduce
1. Workflow for deeplabcut 3d
2. Run: deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=6, calibrate=True, alpha=0.9)

Desktop (please complete the following information about your system):
- OS: Windows 10
- DeepLabCut Version: 2.1.3
- Browser: Chrome

This is my folder of the project:
https://drive.google.com/drive/folders/1OBmSmoNwQOBWTgmxPm-LmpNfIXFl4plY?usp=sharing

**Comment by MMathisLab** [comment] 2020-10-11 21:23
closed as duplicate of #954.

**Closed as completed** 2020-10-11 21:23 UTC
