### ISSUE TITLE
Video Labels are missing

### ISSUE THREAD

**Issue by WrathUM** [DeepLabCut/DeepLabCut#1076] opened 2021-01-09 00:54 UTC
OS: Windows 10
DeepLabCut Version: Version 2.207b
Anaconda env used: GPU

https://github.com/DeepLabCut/DeepLabCut/issues/991

Follow up on the above issue thread. I have added a comment as a follow up to the final comment before it was closed due to inactivity. 

I am wondering if it is possible that the errors found there are a result of hardware being insufficient. 

The Computer being used to make those videos have a NVIDIA GeForce GT 730, Intel i7-7700 CPU and 32 GB of system memory. I just want to see if this has ever happened before and explore if this is a possibility as I am at a loss as to what is causing this problem.

**Comment by MMathisLab** [comment] 2021-01-11 20:51
duplicate of #991

**Closed as completed by MMathisLab** 2021-01-11 20:51 UTC
Labels: duplicate
