### ISSUE TITLE
Issues with video analysis with DLC 2.rc3

### ISSUE THREAD

**Issue by DaBue93** [DeepLabCut/DeepLabCut#1375] opened 2021-07-02 13:33 UTC
********************
DLC 2.rc3 with GUI
Operating System:  CentOS 7 (Linux)
********************
Hello,
I have a question about analyzing video files (.mpg) in the latest version of DLC. The training worked great but now I would like to analyze my videos. This seems to work as well. DLC takes ~ 4-6 min to analyze my video. however, no csv nor h5 file is shown in the output folder. Which is why I can’t create a video then. Additional info: I do a single animal analysis (so not maDLC).

Please place code inside this:

<details><summary>Code output</summary><p>

[Using snapshot-1030000 for model /home/djenderny/DLC/OF/OF_Masterthesis-DJ-2021-06-24/dlc-models/iteration-0/OF_MasterthesisJun24-trainset95shuffle1
2021-07-02 15:22:13.274915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:1a:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2021-07-02 15:22:13.276899: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-02 15:22:13.277009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-02 15:22:13.277026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-07-02 15:22:13.277051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-07-02 15:22:13.278236: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2934 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:1a:00.0, compute capability: 7.5)
Starting to analyze %  /home/djenderny/DLC/OF/male/WT/cropped/OF_08W_2577_WTcropped.mpg
/home/djenderny/DLC/OF/male/WT/cropped  already exists!
Loading  /home/djenderny/DLC/OF/male/WT/cropped/OF_08W_2577_WTcropped.mpg
Duration of video [s]:  304.92 , recorded with  25.0 fps!
Overall # of frames:  7623  found with (before cropping) frame dimensions:  706 722
Starting to extract posture
7676it [02:57, 43.04it/s]                                                                                                                                                                     Starting to analyze %  /home/djenderny/DLC/OF/male/WT/cropped/OF_40W_2484_WTcropped.mpg
/home/djenderny/DLC/OF/male/WT/cropped  already exists!
Loading  /home/djenderny/DLC/OF/male/WT/cropped/OF_40W_2484_WTcropped.mpg
Duration of video [s]:  306.8 , recorded with  25.0 fps!
Overall # of frames:  7670  found with (before cropping) frame dimensions:  730 740
Starting to extract posture
7676it [03:09, 40.51it/s]
Saving results in /home/djenderny/DLC/OF/male/WT/cropped...                                                                                                                                   
Saving csv poses!
7676it [06:08, 20.83it/s]
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.

]

</p></details>

**How to Reproduce the problem**
1. go to "Analyze video"
2. Click on "add video"
3. also wanted to get .csv file
4. analyze video (~3-6 min)
5. No output in the video folder

**Screenshots**
![analyze1](https://user-images.githubusercontent.com/66160679/124281873-77dd8080-db4a-11eb-813d-96f185576478.jpg)

![analyze2](https://user-images.githubusercontent.com/66160679/124281880-790ead80-db4a-11eb-9dc0-c2e408584b16.jpg)

![analyze3](https://user-images.githubusercontent.com/66160679/124281876-78761700-db4a-11eb-9e9a-248fa23d34c8.jpg)

does it make sense to convert the video files? since i can't select .mpg.

**Comment by MMathisLab** [comment] 2021-07-02 15:03
duplicate of: https://forum.image.sc/t/issues-with-video-analysis-with-dlc-2-rc2/54528/3

**Closed as completed by MMathisLab** 2021-07-02 15:03 UTC

**Comment by wfmueller29** [comment] 2021-07-28 19:01
I'm having this same issue. I am working from the terminal on a Linux machine.
