### ISSUE TITLE
RTX 3070: LossTensor is inf or nan

### ISSUE THREAD

**Issue by sasaki-iwateJapn** [DeepLabCut/DeepLabCut#1082] opened 2021-01-15 05:26 UTC
my error when I start training.
Recently,I change new GPU(GTX680 to RTX3070).
I install NewGPU driver and CUDA(vver.10) , cudNN(7.4)
my DLC is do not work.
please help me 

**I use DeepLabCut==2.1.9**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: [Windows 10]
DeepLabCut Version: [2.1.9 and 2.2b5] 
Anaconda env used:Anaconda3

**Describe the problem**

A clear and concise description of what the problem is.

Please place code inside this:

<details><summary>Code output</summary><p>

`The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2]],
 'all_joints_names': ['snout', 'earL', 'earR'],
 'batch_size': 1,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_SD_m_310Dec21\\SD_m_310_sasaki95shuffle1.mat',
 'dataset_type': 'imgaug',
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\htomi\\anaconda3\\envs\\DLC-GPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_SD_m_310Dec21\\Documentation_data-SD_m_310_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 3,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': 'C:\\deeplabcut\\SD_m_310-sasaki-2020-12-21',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\deeplabcut\\SD_m_310-sasaki-2020-12-21\\dlc-models\\iteration-0\\SD_m_310Dec21-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Starting with imgaug pose-dataset loader (=default).
Batch Size is 1
Initializing ResNet
Loading ImageNet-pretrained resnet_50
2021-01-15 13:27:45.379136: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-01-15 13:27:45.556686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce RTX 3070 major: 8 minor: 6 memoryClockRate(GHz): 1.755
pciBusID: 0000:08:00.0
totalMemory: 8.00GiB freeMemory: 6.54GiB
2021-01-15 13:27:45.560892: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2021-01-15 13:31:19.547740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-15 13:31:19.550316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2021-01-15 13:31:19.552057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2021-01-15 13:31:19.553914: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6272 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3070, pci bus id: 0000:08:00.0, compute capability: 8.6)
Max_iters overwritten as 1030000
Display_iters overwritten as 1000
Save_iters overwritten as 50000
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\deeplabcut\\SD_m_310-sasaki-2020-12-21\\dlc-models\\iteration-0\\SD_m_310Dec21-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2]], 'all_joints_names': ['snout', 'earL', 'earR'], 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_SD_m_310Dec21\\SD_m_310_sasaki95shuffle1.mat', 'display_iters': 1000, 'init_weights': 'C:\\Users\\htomi\\anaconda3\\envs\\DLC-GPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_SD_m_310Dec21\\Documentation_data-SD_m_310_95shuffle1.pickle', 'min_input_size': 64, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 3, 'pos_dist_thresh': 17, 'project_path': 'C:\\deeplabcut\\SD_m_310-sasaki-2020-12-21', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': [-90, 90]}}
Starting training....
2021-01-15 13:46:05.941768: E tensorflow/core/kernels/check_numerics_op.cc:185] abnormal_detected_host @0000000203808800 = {1, 0} LossTensor is inf or nan
Traceback (most recent call last):
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: LossTensor is inf or nan : Tensor had NaN values
         [[{{node train_op/CheckNumerics}}]]
         [[{{node train_op/control_dependency}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\train_network.py", line 329, in train_network
    maxiters=maxiters,
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 193, in train_network
    raise e
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 189, in train_network
    allow_growth=allow_growth,
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 255, in train
    feed_dict={learning_rate: current_lr},
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: LossTensor is inf or nan : Tensor had NaN values
         [[node train_op/CheckNumerics (defined at C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py:116) ]]
         [[node train_op/control_dependency (defined at C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py:116) ]]

Caused by op 'train_op/CheckNumerics', defined at:
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\__main__.py", line 20, in <module>
    deeplabcut.launch_dlc()
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\launch_script.py", line 66, in launch_dlc
    app.MainLoop()
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\wx\core.py", line 2166, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\train_network.py", line 329, in train_network
    maxiters=maxiters,
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 189, in train_network
    allow_growth=allow_growth,
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 215, in train
    learning_rate, train_op = get_optimizer(total_loss, cfg)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 116, in get_optimizer
    train_op = slim.learning.create_train_op(loss_op, optimizer)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 439, in create_train_op
    check_numerics=check_numerics)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\contrib\training\python\training\training.py", line 464, in create_train_op
    'LossTensor is inf or nan')
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1075, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): LossTensor is inf or nan : Tensor had NaN values
         [[node train_op/CheckNumerics (defined at C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py:116) ]]
         [[node train_op/control_dependency (defined at C:\Users\htomi\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py:116) ]]`

pip list
(DLC-GPU) C:\Windows\system32>pip list
Package                Version
---------------------- -------------------
absl-py                0.11.0
argon2-cffi            20.1.0
astor                  0.8.1
async-generator        1.10
attrs                  20.3.0
backcall               0.2.0
bayesian-optimization  1.2.0
bleach                 3.2.1
certifi                2020.12.5
cffi                   1.14.4
chardet                4.0.0
click                  7.1.2
colorama               0.4.4
cycler                 0.10.0
Cython                 0.29.21
decorator              4.4.2
deeplabcut             2.1.9
defusedxml             0.6.0
easydict               1.9
entrypoints            0.3
filterpy               1.4.5
gast                   0.4.0
grpcio                 1.31.0
h5py                   2.10.0
idna                   2.10
imageio                2.9.0
imageio-ffmpeg         0.4.3
imgaug                 0.4.0
importlib-metadata     2.0.0
intel-openmp           2021.1.2
ipykernel              5.3.4
ipython                7.19.0
ipython-genutils       0.2.0
ipywidgets             7.6.3
jedi                   0.18.0
Jinja2                 2.11.2
joblib                 1.0.0
jsonschema             3.2.0
jupyter                1.0.0
jupyter-client         6.1.7
jupyter-console        6.2.0
jupyter-core           4.7.0
jupyterlab-pygments    0.1.2
jupyterlab-widgets     1.0.0
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.0
kiwisolver             1.3.1
llvmlite               0.34.0
Markdown               3.3.3
MarkupSafe             1.1.1
matplotlib             3.1.3
mistune                0.8.4
mkl-fft                1.2.0
mkl-random             1.1.1
mkl-service            2.3.0
mock                   4.0.3
moviepy                1.0.1
msgpack                1.0.2
msgpack-numpy          0.4.7.1
nb-conda               2.2.1
nb-conda-kernels       2.3.1
nbclient               0.5.1
nbconvert              6.0.7
nbformat               5.0.8
nest-asyncio           1.4.3
networkx               2.5
notebook               6.1.6
numba                  0.51.1
numexpr                2.7.2
numpy                  1.16.4
opencv-python          4.5.1.48
opencv-python-headless 4.5.1.48
packaging              20.8
pandas                 1.1.5
pandocfilters          1.4.3
parso                  0.8.1
patsy                  0.5.1
pickleshare            0.7.5
Pillow                 8.1.0
pip                    20.3.3
proglog                0.1.9
prometheus-client      0.9.0
prompt-toolkit         3.0.8
protobuf               3.13.0
psutil                 5.8.0
pycparser              2.20
Pygments               2.7.4
pyparsing              2.4.7
pyreadline             2.1
pyrsistent             0.17.3
python-dateutil        2.8.1
pytz                   2020.5
PyWavelets             1.1.1
pywin32                227
pywinpty               0.5.7
PyYAML                 5.3.1
pyzmq                  20.0.0
qtconsole              4.7.7
QtPy                   1.9.0
requests               2.25.1
ruamel.yaml            0.16.12
ruamel.yaml.clib       0.2.2
scikit-image           0.17.2
scikit-learn           0.24.0
scipy                  1.5.2
Send2Trash             1.5.0
setuptools             51.1.2.post20210112
Shapely                1.7.1
six                    1.15.0
statsmodels            0.12.1
tables                 3.6.1
tabulate               0.8.7
tensorboard            1.13.1
tensorflow-estimator   1.13.0
tensorflow-gpu         1.13.1
tensorpack             0.9.8
termcolor              1.1.0
terminado              0.9.2
testpath               0.4.4
threadpoolctl          2.1.0
tifffile               2021.1.11
tornado                6.1
tqdm                   4.56.0
traitlets              5.0.5
urllib3                1.26.2
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.36.2
widgetsnbextension     3.5.1
wincertstore           0.2
wxPython               4.0.4
zipp                   3.4.0

nvcc -V
(DLC-GPU) C:\Windows\system32>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130

nvidia-smi
(DLC-GPU) C:\Windows\system32>nvidia-smi
Fri Jan 15 14:24:58 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.89       Driver Version: 460.89       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3070   WDDM  | 00000000:08:00.0  On |                  N/A |
|  0%   41C    P8    14W / 220W |    581MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1548    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      2396    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A      5848    C+G   ...es.TextInput.InputApp.exe    N/A      |
|    0   N/A  N/A      6204    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      7040    C+G   ...artMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A      7432    C+G   ...w5n1h2txyewy\SearchUI.exe    N/A      |
|    0   N/A  N/A      7940    C+G   ...wekyb3d8bbwe\Video.UI.exe    N/A      |
|    0   N/A  N/A      8148    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      9396    C+G   ...ekyb3d8bbwe\YourPhone.exe    N/A      |
+-----------------------------------------------------------------------------+

</p></details>

**How to Reproduce the problem**

**Screenshots**

**Additional context**

**Comment by jeylau** [comment] 2021-01-15 08:41
Duplicate of #1017

**Closed as completed by jeylau** 2021-01-15 08:41 UTC
