### ISSUE TITLE
2.0.5.1 GUI cannot crop or grab frames Windows 10: 'MainFrame' object has no attribute 'new_x1'

### ISSUE THREAD

**Issue by effiek9999** [DeepLabCut/DeepLabCut#251] opened 2019-03-27 15:18 UTC
OS: Windows 10
DeepLabCut version: 2.0.5
Anaconda 3 environment

Problem description:

Steps to reproduce problem:

(1) deeplabcut.extract_frames(config_path, 'manual', crop=True)

(2) GUI comes up and I select an avi file (see screenshots)

(3) I cannot crop and load frames doesn't do anything
Errors attached: 'MainFrame' object has no attribute 'new_x1'
I cannot select any cropping area and hitting 'Set cropping parameters' doesn't do anything

![Screenshot (10)](https://user-images.githubusercontent.com/3596849/55088390-09afd680-5082-11e9-834e-531a924654bf.png)
![Screenshot (12)](https://user-images.githubusercontent.com/3596849/55088403-0fa5b780-5082-11e9-8d9c-14c024e2f3f8.png)
![Screenshot (14)](https://user-images.githubusercontent.com/3596849/55088409-116f7b00-5082-11e9-9eab-811274700e2b.png)

**Comment by meet10may** [comment] 2019-03-30 11:23
It seems the issue is while creating the project in **windows**, the symlinks are copied over to the variable `video_sets`  in the config.yaml file. You can check in your config file, the variable video_sets should have the full path of symlink rather than the real path.  
When you try to open the video it opens the real path and not the symlink. When cropping, the toolbox tries to access the croping parameters of the video from the config.yaml file and  because the config file has symlink, it could not find the parameters and throws error. 
**FIX:** 
Either you can copy the video while creating the project.
or
Change the line 133 in new.py under create_project which is 
`rel_video_path = os.path.realpath(video)` 
to
 `rel_video_path=str(Path.resolve(Path(video)))`
and reinstall DeepLabCut from your local repository.
We will release this fix soon.
Also, you do not need to specify `crop=True` for manual extraction, as the GUI will anyway ask the user if you need to crop. The argument `crop=True` is mainly for automatic extraction.
 
Hope it helps!

**Comment by AlexEMG** [comment] 2019-03-31 16:52
Put it in repo. Will be also pip released in the next version

**Closed as completed by AlexEMG** 2019-03-31 16:52 UTC

**Comment by effiek9999** [comment] 2019-04-03 20:19
The problem now is that ipython itself gives errors when I use the double slashes. So I updated deeplabcut with the new.py fix (I hope I did the reinstallation correctly - I put all the latest DeepLabCut files in C:\Users\Usertytell_admin\Anaconda3\Lib\site-packages\deeplabcut and ran conda env update -f dlc-windowsGPU.yaml) but now you can see there are other problems according to my screenshot. But I also wonder if I did the reinstallation correctly because you can see in the screenshot that I used deeplabcut.create_new_project with double slashes and it gave new errors. But in ipython I set config_path = 'c:\Users\Usertytell_admin\dlc_projects\dlc-windowsCPU.yaml' and I got errors shown in screenshot #2.

I noticed the UseOverviewGuide has been updated with single slashes for paths on Windows (it used to have double slashes). I tried those instructions and ran into these problems.


![Screenshot (22)](https://user-images.githubusercontent.com/3596849/55510387-33da3900-562c-11e9-9e61-dcb4feaed1ea.png)

![Screenshot (24)](https://user-images.githubusercontent.com/3596849/55510679-c24eba80-562c-11e9-96c0-cec0b95b0825.png)

**Comment by meet10may** [comment] 2019-04-03 21:23
For the first error:
It seems the video file cannot be opened. May be you need to double check the path of the video file. When creating the new project, you need to pass the path of the real video file. Not sure, but the path you passed i.e. C:/Users_tyteladmin/dlc_projects/* seems to be a symlink of a video that in somewhere in C:/Users_tyteladmin/Anaconda3/envs/ 
There is something incorrect with the video file path!

For the second error:
In general, when passing the path in `windows` you either need to give double backslashes (e.g. C:\ \Users\ \ ) or use 'r' ('rC:\Users\). Please check here for more details:
<https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips>

**Comment by effiek9999** [comment] 2019-04-04 11:37
Ah I thought there was a typo in the documentation so I didn't follow your suggestion exactly. Thank you so much, I will try this.

**Comment by MMathisLab** [comment] 2019-04-04 12:04
GitHub can change \ \ to display \  , - i even have to add a space between \ and \ just to show you here - but Windows *always* needs \ \ - another reason to just use Linux! ;)
