### ISSUE TITLE
Error when extracting outlier frames

### ISSUE THREAD

**Issue by Andrianarivelo** [DeepLabCut/DeepLabCut#2213] opened 2023-04-20 15:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello,

I have trained a network and analyzed my videos but at the refinement step, I have trouble running deeplabcut.extract_outlier_frames, it never launches and gives this error: TypeError: sum() got an unexpected keyword argument 'level'
Below is the full log output.
I just want to know if you guys are familiar with this log output and have an idea of what's going on. 

Thanks, 

### Operating System

operating system: UBUNTU 20.04

### DeepLabCut version

dlc version: 2.2.1 

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1.activate deeplabcut environment
2.set config_path
3.set videos path
4.extract outlier frames

### Relevant log output

```shell
In [6]: deeplabcut.extract_outlier_frames(config_path, videos, shuffle=1, automatic=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 deeplabcut.extract_outlier_frames(config_path, videos, shuffle=1, automatic=True)

File ~/.conda/envs/dlc22/lib/python3.8/site-packages/deeplabcut/refine_training_dataset/outlier_frames.py:338, in extract_outlier_frames(config, videos, videotype, shuffle, trainingsetindex, outlieralgorithm, comparisonbodyparts, epsilon, p_bound, ARdegree, MAdegree, alpha, extractionalgorithm, automatic, cluster_resizewidth, cluster_color, opencv, savelabeled, destfolder, modelprefix, track_method)
    336 temp_dt = df_temp.diff(axis=0) ** 2
    337 temp_dt.drop("likelihood", axis=1, level="coords", inplace=True)
--> 338 sum_ = temp_dt.sum(axis=1, level=1)
    339 ind = df_temp.index[(sum_ > epsilon ** 2).any(axis=1)].tolist()
    340 Indices.extend(ind)

File ~/.conda/envs/dlc22/lib/python3.8/site-packages/pandas/core/generic.py:11519, in NDFrame._add_numeric_operations.<locals>.sum(self, axis, skipna, numeric_only, min_count, **kwargs)
  11500 @doc(  # type: ignore[misc]
  11501     _num_doc,
  11502     desc="Return the sum of the values over the requested axis.\n\n"
   (...)
  11517     **kwargs,
  11518 ):
> 11519     return NDFrame.sum(self, axis, skipna, numeric_only, min_count, **kwargs)

File ~/.conda/envs/dlc22/lib/python3.8/site-packages/pandas/core/generic.py:11287, in NDFrame.sum(self, axis, skipna, numeric_only, min_count, **kwargs)
  11279 def sum(
  11280     self,
  11281     axis: Axis | None = None,
   (...)
  11285     **kwargs,
  11286 ):
> 11287     return self._min_count_stat_function(
  11288         "sum", nanops.nansum, axis, skipna, numeric_only, min_count, **kwargs
  11289     )

File ~/.conda/envs/dlc22/lib/python3.8/site-packages/pandas/core/generic.py:11259, in NDFrame._min_count_stat_function(self, name, func, axis, skipna, numeric_only, min_count, **kwargs)
  11247 @final
  11248 def _min_count_stat_function(
  11249     self,
   (...)
  11256     **kwargs,
  11257 ):
  11258     if name == "sum":
> 11259         nv.validate_sum((), kwargs)
  11260     elif name == "prod":
  11261         nv.validate_prod((), kwargs)

File ~/.conda/envs/dlc22/lib/python3.8/site-packages/pandas/compat/numpy/function.py:82, in CompatValidator.__call__(self, args, kwargs, fname, max_fname_arg_count, method)
     80     validate_kwargs(fname, kwargs, self.defaults)
     81 elif method == "both":
---> 82     validate_args_and_kwargs(
     83         fname, args, kwargs, max_fname_arg_count, self.defaults
     84     )
     85 else:
     86     raise ValueError(f"invalid validation method '{method}'")

File ~/.conda/envs/dlc22/lib/python3.8/site-packages/pandas/util/_validators.py:221, in validate_args_and_kwargs(fname, args, kwargs, max_fname_arg_count, compat_args)
    216         raise TypeError(
    217             f"{fname}() got multiple values for keyword argument '{key}'"
    218         )
    220 kwargs.update(args_dict)
--> 221 validate_kwargs(fname, kwargs, compat_args)

File ~/.conda/envs/dlc22/lib/python3.8/site-packages/pandas/util/_validators.py:162, in validate_kwargs(fname, kwargs, compat_args)
    140 """
    141 Checks whether parameters passed to the **kwargs argument in a
    142 function `fname` are valid parameters as specified in `*compat_args`
   (...)
    159 map to the default values specified in `compat_args`
    160 """
    161 kwds = kwargs.copy()
--> 162 _check_for_invalid_keys(fname, kwargs, compat_args)
    163 _check_for_default_values(fname, kwds, compat_args)

File ~/.conda/envs/dlc22/lib/python3.8/site-packages/pandas/util/_validators.py:136, in _check_for_invalid_keys(fname, kwargs, compat_args)
    134 if diff:
    135     bad_arg = list(diff)[0]
--> 136     raise TypeError(f"{fname}() got an unexpected keyword argument '{bad_arg}'")

TypeError: sum() got an unexpected keyword argument 'level'

In [7]: deeplabcut.__version__
Out[7]: '2.2.1'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment] 2023-04-21 09:33
Duplicate of #2202

The answer is given [here](https://github.com/DeepLabCut/DeepLabCut/issues/2202#issuecomment-1503105312) 😊

**Closed as completed by jeylau** 2023-04-21 09:33 UTC

**Comment by Andrianarivelo** [comment] 2023-04-21 13:36
Oh great thanks ! It's fixed ! I missed it sorry for the double post

**Comment by jeylau** [comment] 2023-04-21 13:39
No worries, I was working on it and pushing it just as you closed the issue ☺️
