### ISSUE TITLE
ticking *adjust marker size box* interferes with *labeling* and *zoom*  in GUI

### ISSUE THREAD

**Issue by WernTanj** [DeepLabCut/DeepLabCut#136] opened 2018-11-28 14:43 UTC
windows 7, dlc 2.0.1.

1) select frames to label
2) tick adjust marker size and change it
3) right click on bodypart to label  - not responsive

OR

1) select frames to label
2) right click on first bodypart to label 
3) tick adjust marker size and change it
4) zoom not responsive

**Comment by MMathisLab** [comment] 2018-11-28 15:17
Duplicate of #129. Closing

**Closed as completed by MMathisLab** 2018-11-28 15:17 UTC
Labels: duplicate

**Comment by MMathisLab** [comment] 2018-11-28 16:17
Yes, dotsize curretnly refers to the plotting for creating videos. But I could pass that to Guo too, good suggestion. I’ll make a note for a future release.
