### ISSUE TITLE
Issue with starting DLC on M2 Mac, Numpy issue

### ISSUE THREAD

**Issue by zque-u** [DeepLabCut/DeepLabCut#2556] opened 2024-04-09 10:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello.

I installed DLC with miniconda and the lastest .yaml file.
When I run `python -m deeplabcut`, it returned with the following error:
```
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
```

I have uploaded numpy to the lastest version 1.26.4 as described in [this issue](https://github.com/DeepLabCut/DeepLabCut/issues/2544) but this error persists.

Below is the return from `pip list`
```
absl-py                          2.1.0
alabaster                        0.7.16
anyio                            3.7.1
app-model                        0.2.6
appdirs                          1.4.4
appnope                          0.1.3
argon2-cffi                      21.3.0
argon2-cffi-bindings             21.2.0
arrow                            1.2.3
asttokens                        2.2.1
astunparse                       1.6.3
async-lru                        2.0.3
attrs                            23.1.0
Babel                            2.12.1
backcall                         0.2.0
beautifulsoup4                   4.12.2
bleach                           6.0.0
blinker                          1.6.2
blosc2                           2.6.2
build                            1.2.1
cachey                           0.2.1
certifi                          2023.5.7
cffi                             1.15.1
charset-normalizer               3.2.0
click                            8.1.4
cloudpickle                      3.0.0
comm                             0.1.3
contourpy                        1.1.0
cryptography                     41.0.1
cycler                           0.11.0
dask                             2024.4.1
dask-expr                        1.0.10
dask-image                       2023.8.1
datajoint                        0.14.1
datatops                         0.2.2
debugpy                          1.6.7
decorator                        5.1.1
deeplabcut                       2.2.3
defusedxml                       0.7.1
dill                             0.3.6
docstring_parser                 0.16
docutils                         0.17.1
executing                        1.2.0
fastjsonschema                   2.17.1
filelock                         3.12.2
filterpy                         1.4.5
Flask                            2.3.2
flatbuffers                      24.3.25
fonttools                        4.40.0
fqdn                             1.5.1
freetype-py                      2.4.0
frz-jupyterlab-variableinspector 0.1.4
fsspec                           2024.3.1
gast                             0.5.4
google-pasta                     0.2.0
grpcio                           1.62.1
h5py                             3.10.0
HeapDict                         1.0.1
hsluv                            5.0.4
idna                             3.4
imageio                          2.34.0
imagesize                        1.4.1
imgaug                           0.4.0
importlib_metadata               7.1.0
in-n-out                         0.2.0
ipykernel                        6.24.0
ipython                          8.14.0
ipywidgets                       8.0.7
isoduration                      20.11.0
itsdangerous                     2.1.2
jedi                             0.18.2
Jinja2                           3.1.2
joblib                           1.3.1
json5                            0.9.14
jsonpointer                      2.4
jsonschema                       4.18.3
jsonschema-specifications        2023.6.1
jupyter_client                   8.3.0
jupyter_core                     5.3.1
jupyter-events                   0.6.3
jupyter-lsp                      2.2.0
jupyter_server                   2.7.0
jupyter_server_terminals         0.4.4
jupyterlab                       4.0.3
jupyterlab-pygments              0.2.2
jupyterlab_server                2.23.0
jupyterlab-widgets               3.0.8
keras                            3.2.0
kiwisolver                       1.4.4
lazy_loader                      0.4
libclang                         18.1.1
llvmlite                         0.42.0
locket                           1.0.0
magicgui                         0.8.2
Markdown                         3.6
markdown-it-py                   3.0.0
MarkupSafe                       2.1.3
matplotlib                       3.7.2
matplotlib-inline                0.1.6
mdurl                            0.1.2
minio                            7.1.15
mistune                          3.0.1
ml-dtypes                        0.3.2
mpmath                           1.3.0
msgpack                          1.0.8
msgpack-numpy                    0.4.8
namex                            0.0.7
napari                           0.4.18
napari-console                   0.0.9
napari-deeplabcut                0.2.1.6
napari-plugin-engine             0.2.0
napari-svg                       0.1.10
natsort                          8.4.0
nbclient                         0.8.0
nbconvert                        7.6.0
nbformat                         5.9.1
ndindex                          1.8
nest-asyncio                     1.5.6
networkx                         3.3
nibabel                          5.1.0
nma-ibl                          0.1.0
notebook_shim                    0.2.3
npe2                             0.7.5
numba                            0.59.1
numexpr                          2.10.0
numpy                            1.26.4
numpydoc                         1.5.0
opencv-python                    4.9.0.80
opencv-python-headless           4.9.0.80
opt-einsum                       3.3.0
optree                           0.11.0
otumat                           0.3.1
overrides                        7.3.1
packaging                        23.1
pandas                           2.0.3
pandocfilters                    1.5.0
parso                            0.8.3
partd                            1.4.1
patsy                            0.5.3
pexpect                          4.8.0
pickleshare                      0.7.5
Pillow                           10.0.0
PIMS                             0.6.1
Pint                             0.23
pip                              24.0
platformdirs                     3.8.1
pooch                            1.8.1
prometheus-client                0.17.1
prompt-toolkit                   3.0.39
protobuf                         4.25.3
psutil                           5.9.5
psygnal                          0.11.0
ptyprocess                       0.7.0
pure-eval                        0.2.2
py-cpuinfo                       9.0.0
pyarrow                          15.0.2
pyconify                         0.1.6
pycparser                        2.21
pydantic                         1.10.15
pydantic-compat                  0.1.2
pydot                            1.4.2
Pygments                         2.15.1
pykalman                         0.9.5
PyMySQL                          1.1.0
PyOpenGL                         3.1.7
pyparsing                        3.0.9
pyproject_hooks                  1.0.0
python-dateutil                  2.8.2
python-json-logger               2.0.7
pytz                             2023.3
PyYAML                           6.0
pyzmq                            25.1.0
qtconsole                        5.5.1
QtPy                             2.4.1
referencing                      0.29.1
requests                         2.31.0
rfc3339-validator                0.1.4
rfc3986-validator                0.1.1
rich                             13.7.1
rpds-py                          0.8.10
ruamel.yaml                      0.18.6
ruamel.yaml.clib                 0.2.8
scikit-image                     0.22.0
scikit-learn                     1.3.0
scipy                            1.11.1
seaborn                          0.12.2
Send2Trash                       1.8.2
setuptools                       65.5.0
shapely                          2.0.3
shellingham                      1.5.4
six                              1.16.0
slicerator                       1.1.0
sniffio                          1.3.0
snowballstemmer                  2.2.0
soupsieve                        2.4.1
Sphinx                           4.5.0
sphinxcontrib-applehelp          1.0.8
sphinxcontrib-devhelp            1.0.6
sphinxcontrib-htmlhelp           2.0.5
sphinxcontrib-jsmath             1.0.1
sphinxcontrib-qthelp             1.0.7
sphinxcontrib-serializinghtml    1.1.10
stack-data                       0.6.2
statsmodels                      0.14.0
superqt                          0.6.3
sympy                            1.12
tables                           3.9.2
tabulate                         0.9.0
tensorboard                      2.16.2
tensorboard-data-server          0.7.2
tensorflow                       2.16.1
tensorflow-io-gcs-filesystem     0.36.0
tensorpack                       0.11
termcolor                        2.4.0
terminado                        0.17.1
tf-slim                          1.1.0
threadpoolctl                    3.1.0
tifffile                         2024.2.12
tinycss2                         1.2.1
tomli_w                          1.0.0
toolz                            0.12.1
torch                            2.0.1
tornado                          6.3.2
tqdm                             4.65.0
traitlets                        5.9.0
typer                            0.12.2
typing_extensions                4.7.1
tzdata                           2023.3
uri-template                     1.3.0
urllib3                          2.0.3
vibecheck                        0.0.3
vispy                            0.12.2
watchdog                         3.0.0
wcwidth                          0.2.6
webcolors                        1.13
webencodings                     0.5.1
websocket-client                 1.6.1
Werkzeug                         2.3.6
wheel                            0.43.0
widgetsnbextension               4.0.8
wrapt                            1.16.0
zipp                             3.18.1
```

I appreciate any forms of help. Thank you very much.

### Operating System

macOS Sonoma 14.4

### DeepLabCut version

2.2.3

### DeepLabCut mode

single animal

### Device type

Apple M2

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment] 2024-04-12 16:12
Hi @zq73939133, as this is a duplicate of #2544 I'll close it and we can discuss in the original issue.

**Closed as not planned by n-poulsen** 2024-04-12 16:12 UTC
