### ISSUE TITLE
Issue with labeling, keypoints don't switch to other bodyparts

### ISSUE THREAD

**Issue by FarahnazYF** [DeepLabCut/DeepLabCut#2387] opened 2023-09-17 23:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi.

I'm trying to label 8 different body parts in extracted frames from one video (one animal), but in the napari, the keypoints don't switch to other body parts and it always shows the first defined body part. (In the keypoints control, I cannot activate 'show trails'.)

I updated everything, still I couldn't fix the problem. I would appreciate any help.
I'm using GUI, ipython.
 
![2023-09-17_221800](https://github.com/DeepLabCut/DeepLabCut/assets/144938166/55cd6f35-1881-4c65-9a39-775b2415e3f1)

https://github.com/DeepLabCut/DeepLabCut/assets/144938166/d355fd42-4ef9-4198-ab8e-bb808d91d689

Thank you so much in advance for your help.

### Operating System

operating system: windows 10

### DeepLabCut version

dlc version: 2.3.5
napari: 0.4.18

### DeepLabCut mode

single animal

### Device type

CPU

### Steps To Reproduce

1. conda activate deeplabcut
2. ipython
3. import deeplabcut
4. deeplabcut.launch_dlc()
5. load project (my config file)
6. labeling
7. napari

### Anything else?

I've attached pictures of my conda list and config file, if it helps.

![conda list](https://github.com/DeepLabCut/DeepLabCut/assets/144938166/590d62d7-4ec7-440f-8796-2be2b7d7381c)
![config](https://github.com/DeepLabCut/DeepLabCut/assets/144938166/2243d6b7-23e0-4396-b402-b9c24fa02a05)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment] 2023-09-18 17:18
@FarahnazYF very strange, it's a napari-deeplabcut issue we cannot reproduce... at least on the stable branch of napari, see you are maybe ahead of that though:

![Screen Shot 2023-09-18 at 7 19 08 PM](https://github.com/DeepLabCut/DeepLabCut/assets/28102185/befdab15-ad88-4954-91b5-8d88641ea385)


can you run `pip install --upgrade --force-reinstall 'deeplabcut[gui]' ` and then `pip install napari-deeplabcut==0.2.1`--> we are also tracking it here: https://github.com/DeepLabCut/napari-deeplabcut/issues/99 

worst case, you can also pip install napari-deeplabcut==0.2.0` to roll back last nights release!

Lastly thanks for the very good bug report and video!! 🙏

**Comment by MMathisLab** [comment] 2023-09-18 17:26
Okay, I can reproduce the error, will post updated on fixes here: https://github.com/DeepLabCut/napari-deeplabcut/issues/99

**Comment by jeylau** [comment] 2023-09-18 17:27
Great! Let me look at it and I'll push a fix and a new minor release!

**Comment by jeylau** [comment] 2023-09-18 18:00
I pushed the fix here https://github.com/DeepLabCut/napari-deeplabcut/pull/100, we'll release a patch soon 😊

**Comment by jeylau** [comment] 2023-09-18 18:42
@FarahnazYF, the patch is now live, you can install with `pip install -U napari-deeplabcut`.

**Closed as completed by jeylau** 2023-09-18 18:42 UTC
Labels: bug, GUI

**Comment by FarahnazYF** [comment] 2023-09-18 19:30
Dear @MMathisLab  and @jeylau,

Thank you so much for your quick response and valuable help. I did what you said and now I can label the frames without any problem. 

Best.
