### ISSUE TITLE
Trying to use deeplabcut.label_frames() in HPC but it results error

### ISSUE THREAD

**Issue by mirramezani** [DeepLabCut/DeepLabCut#2510] opened 2024-02-07 09:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm trying to use deeplabcut in a supercomputer with GPU. I load all necessary modules like:  CUDA and
cuDNN/CUDA. It successfully  extracts the frames but when I'm using deeplabcut.label_frames(), it results an error as below:

```
Loading DLC 2.2.3...
Starting GUI...
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 13.54  seconds.
Extracting and downsampling... 325  frames from the video.
325it [00:03, 84.76it/s]
Kmeans clustering ... (this might take a while)
/home/m.mirramezani@gmail.com/.conda/envs/deeplabcut/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1934: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=3)
Frames were successfully extracted, for the videos listed in the config.yaml file.

You can now label the frames using the function 'label_frames' (Note, you should label frames extracted from diverse videos (and many videos; we do not recommend training on single videos!)).
Traceback (most recent call last):
  File "/home/m.mirramezani@gmail.com/.conda/envs/deeplabcut/lib/python3.10/site-packages/deeplabcut/gui/label_frames.py", line 232, in label_frames
    label_frames(self.config)
  File "/home/m.mirramezani@gmail.com/.conda/envs/deeplabcut/lib/python3.10/site-packages/deeplabcut/gui/label_frames.py", line 101, in label_frames
    labeling_toolbox.show(config, config3d, sourceCam, imtypes, jump_unlabeled)
  File "/home/m.mirramezani@gmail.com/.conda/envs/deeplabcut/lib/python3.10/site-packages/deeplabcut/gui/labeling_toolbox.py", line 970, in show
    frame = MainFrame(None, config, imtypes, config3d, sourceCam, jump_unlabeled).Show()
  File "/home/m.mirramezani@gmail.com/.conda/envs/deeplabcut/lib/python3.10/site-packages/deeplabcut/gui/labeling_toolbox.py", line 273, in __init__
    vSplitter.SplitVertically(
TypeError: SplitterWindow.SplitVertically(): argument 'sashPosition' has unexpected type 'float'
^C
```

### Operating System

Linux

### DeepLabCut version

2.2.3

### DeepLabCut mode

single animal

### Device type

gpu

### Relevant log output

```shell
Loading DLC 2.2.3...
Starting GUI...
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 13.54  seconds.
Extracting and downsampling... 325  frames from the video.
325it [00:03, 84.76it/s]
Kmeans clustering ... (this might take a while)
/home/m.mirramezani@gmail.com/.conda/envs/deeplabcut/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1934: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=3)
Frames were successfully extracted, for the videos listed in the config.yaml file.

You can now label the frames using the function 'label_frames' (Note, you should label frames extracted from diverse videos (and many videos; we do not recommend training on single videos!)).
Traceback (most recent call last):
  File "/home/m.mirramezani@gmail.com/.conda/envs/deeplabcut/lib/python3.10/site-packages/deeplabcut/gui/label_frames.py", line 232, in label_frames
    label_frames(self.config)
  File "/home/m.mirramezani@gmail.com/.conda/envs/deeplabcut/lib/python3.10/site-packages/deeplabcut/gui/label_frames.py", line 101, in label_frames
    labeling_toolbox.show(config, config3d, sourceCam, imtypes, jump_unlabeled)
  File "/home/m.mirramezani@gmail.com/.conda/envs/deeplabcut/lib/python3.10/site-packages/deeplabcut/gui/labeling_toolbox.py", line 970, in show
    frame = MainFrame(None, config, imtypes, config3d, sourceCam, jump_unlabeled).Show()
  File "/home/m.mirramezani@gmail.com/.conda/envs/deeplabcut/lib/python3.10/site-packages/deeplabcut/gui/labeling_toolbox.py", line 273, in __init__
    vSplitter.SplitVertically(
TypeError: SplitterWindow.SplitVertically(): argument 'sashPosition' has unexpected type 'float'
^C
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment] 2024-02-08 13:22
Hi @mirramezani, this is a duplicate of #1930 - to fix this, you need to update the code yourself as answered in the fix and re-install DeepLabCut.

The other option would be to update the DeepLabCut GUI and switch to napari-based annotation.

**Closed as completed by n-poulsen** 2024-02-08 13:22 UTC
Labels: GUI
