### ISSUE TITLE
Problem saving refined labels.

### ISSUE THREAD

**Issue by ericabusch** [DeepLabCut/DeepLabCut#374] opened 2019-07-23 21:03 UTC
*Your Operating system and DeepLabCut version*
I am using Ubuntu 16.04 and DeepLabCut version 2.0.6.2

*Please state your operating system, env, and which version of DeepLabCut you are using.*
Ubuntu 16.04 with provided Anaconda Env & DeepLabCut 2.0.6.2

*Please complete the following information about your system:*

OS: Ubuntu 16.04
DeepLabCut Version 2.0.6.2
Browser Firefox

*Describe the problem*
My refined labels do not appear to be saving correctly. When I refine labels and then save and go to check my labels, certain frames do not appear to be updating. About 85% of them save as expected, but the remaining 15% do not save with the refinements I made. Some of these frames appear to be labeled identically to the labels I placed on other frames from a different video in the training dataset, as shown in the images below. I'm uncertain how to reproduce the problem, as it only happens about 15% of the time but it interferes with performance.  

![img002](https://user-images.githubusercontent.com/37850800/61747803-85314400-ad53-11e9-8303-bdbbe8267b1d.png)
This frame is clearly labeled as I have labeled a different frame. I have refined the labels on this particular frame, saved it, and gone to check the labels and it still has not updated, whereas others I refined have updated, as shown in the following image (from the same video). This problem has persisted for several particular frames across several iterations of this project.
![img007](https://user-images.githubusercontent.com/37850800/61747852-af830180-ad53-11e9-88d2-456c480433c2.png)

**Comment by ericabusch** [comment] 2019-07-23 21:11
I am using Ubuntu 16.04 and DeepLabCut version 2.0.6.2

My refined labels do not appear to be saving correctly. When I refine labels and then save and go to check my labels, certain frames do not appear to be updating. About 85% of them save as expected, but the remaining 15% do not save with the refinements I made. Some of these frames appear to be labeled identically to the labels I placed on other frames from a different video in the training dataset, as shown in the images below.

![img002](https://user-images.githubusercontent.com/37850800/61747803-85314400-ad53-11e9-8303-bdbbe8267b1d.png)
This frame is clearly labeled as I have labeled a different frame. I have refined the labels on this particular frame, saved it, and gone to check the labels and it still has not updated, whereas others I refined have updated, as shown in the following image (from the same video). This problem has persisted for several particular frames across several iterations of this project.
![img007](https://user-images.githubusercontent.com/37850800/61747852-af830180-ad53-11e9-88d2-456c480433c2.png)

**Comment by MMathisLab** [comment] 2019-07-23 21:17
Please fill in the template that was originally provided, then we will assist you. 

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

**Please complete the following information about your system:**

OS: [e.g. iOS, Windows 10, etc]
DeepLabCut Version [e.g. 22] (please check with import deeplabcut, deeplabcut.version)
Browser [e.g. chrome, safari]

**Describe the problem**

A clear and concise description of what the problem is.

How to Reproduce the problem
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Screenshots
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by MMathisLab** [comment] 2019-07-23 22:39
can you confirm you did these steps:

(1) extract frames to refine
(2) open them in the refine_labels GUI, edit, then hit save. 
(3) merge project 
(4) run check labels?

**Comment by ericabusch** [comment] 2019-07-23 22:41
Yes, I definitely did these steps. The images from my post are from running deeplabcut.check_labels after all of these steps.

**Comment by MMathisLab** [comment] 2019-07-23 22:44
can you clarify how many iterations you are doing?

> This problem has persisted for several particular frames across several iterations of this project.

**Comment by MMathisLab** [comment] 2019-07-23 22:46
can you also confirm/post a screenshot that when you now open the merged 'collect_data.h5' in the label_frames GUI that the points are misplaced?

**Comment by ericabusch** [comment] 2019-07-23 23:37
After running into this error across 4 iterations of my model in one project, I created a new project with new copies of the labeled dataset and trained a new model for 1030000 training iterations, then refined the labels and retrained for 950000 iterations. I still had the same issues with the same particular frames. 

<img width="1009" alt="Screen Shot 2019-07-23 at 16 21 15" src="https://user-images.githubusercontent.com/37850800/61754398-e8c56c80-ad67-11e9-8d30-a07f606a2ae6.png">
I saved and merged after updating the points and when I call check_labels and create the labeled data directories, it still shows: 
<img width="960" alt="Screen Shot 2019-07-23 at 16 30 46" src="https://user-images.githubusercontent.com/37850800/61754524-540f3e80-ad68-11e9-8013-57f221686c28.png">


However, this isn't for all of the frames -- most frames update as expected. It seems to be just the first 2 or 3 frames that do not update.

**Comment by MMathisLab** [comment] 2019-07-24 18:08
is the above frame also like this in the GUI? 

![](https://user-images.githubusercontent.com/37850800/61754524-540f3e80-ad68-11e9-8013-57f221686c28.png)

**Comment by ericabusch** [comment] 2019-07-24 19:19
Yes, when I reopen it in the GUI it appears like this instead of with my updates

**Comment by MMathisLab** [comment] 2019-07-24 21:47
okay thanks. Could you make a short screen video of this, i.e. open the frame in the refinement, move points, save, close, merge, run check labels? If you don't want to share publicly please feel free to email me: mathis@rowland.harvard.edu - it's just that we cannot reproduce the issue. 

It may be that some of your frames are corrupt, but we'd like to understand why. So, could you also share one of the raw imgs that doesn't save properly, and what video type are you generating these from? I.e. do you see the same errors if you converted video to mp4, ran analyze_videos then extracted outliers?

**Comment by MMathisLab** [comment] 2019-07-26 19:56
Just for those following along; we could not reproduce the error even on @ericabusch data on our computer, so it's unclear what is the issue in saving the images on their end; i.e. the file is being written correctly from the refinement gui...

**Closed as completed by MMathisLab** 2019-07-26 19:56 UTC
