### ISSUE TITLE
refine tracklets drag not work neither mouse choice

### ISSUE THREAD

**Issue by orchidwen** [DeepLabCut/DeepLabCut#1013] opened 2020-11-27 08:53 UTC
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). 
Please fill out the template completely, including the full "TRACEBACK" and input code that you ran to hit this error.

**Describe the bug**
![image](https://user-images.githubusercontent.com/70895934/100429497-5dcd5280-30d0-11eb-92ee-593d717cc759.png)
[](url)
I can not choose mouse1 or mouse2 when I CLICK ON the refine tracklets GUI
Besides, the drag function seems not working that little labels could be dragged. Most of the labels can not be dragged. 

**Desktop (please complete the following information about your system):**
 -ubantu 18.04
 - DeepLabCut Version 2.2b8
 - multi-animal tracking
 - chrome

**To Reproduce**
Steps to reproduce the behavior, i.e.:
4. the input code you used (i.e. `deeplabcut.train_network( .... )`)
4. See error:

<details><summary>TRACEBACK</summary><p>

```python

^do not delete the above "<details><summary>TRACEBACK</summary><p>" or the ```python part!
PLACE YOUR CODE HERE!!!  
do not delete below this line, leave the blank line and the ```

```
</p></details>

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (but please post the code output above, not images of code!)

**Additional context**

**Comment by MMathisLab** [comment] 2020-11-28 13:34
Hi @orchidwen I can confirm on my ubuntu 18.04 LTS system all hotkeys are functional and working. Are you using wxPython 4.0.4? 

You should also upgrade to 2.1.9, it as more features for maDLC.

**Comment by Wutaijing9** [comment] 2020-12-11 05:44
> Hi @orchidwen I can confirm on my ubuntu 18.04 LTS system all hotkeys are functional and working. Are you using wxPython 4.0.4?
> 
> You should also upgrade to 2.1.9, it as more features for maDLC.
I am using wxpython 4.0.4, dlc 2.1.9. python 3.7.9, and once again, refine tracklets I can not choose mouse. Besides, the labels on the mouse can not be dragged.

**Comment by jeylau** [comment] 2021-01-04 16:30
@Wutaijing9, the matplotlib button widget can be a little hard to click onto. Make sure it is correctly checked (there should be a small black tick on its left); hitting 'D' is safest 😃.
What do you mean when you say you cannot choose a mouse? If you click on the legend bars at the top and see no changes, it is normal: you'd first need to click on a keypoint (which seems to work since one trace is shown in the right panel) and only then assign it a different ID.
Last point: before moving to tracklet stitching, please make sure detections and assembled animals look good (e.g., using `deeplabcut.create_video_with_all_detections` or `deeplabcut.utils.make_labeled_video.create_video_from_pickled_tracks`. I find it surprising that keypoints on a single mouse are found to belong to 2 individuals.

**Comment by MMathisLab** [comment] 2021-01-06 00:22
Also, you should update to `wxPython 4.0.7.post2`

**Closed as completed by MMathisLab** 2021-01-06 00:22 UTC
Labels: maDLC

**Comment by Wutaijing9** [comment] 2021-01-07 04:47
> @Wutaijing9, the matplotlib button widget can be a little hard to click onto. Make sure it is correctly checked (there should be a small black tick on its left); hitting 'D' is safest 😃.
> What do you mean when you say you cannot choose a mouse? If you click on the legend bars at the top and see no changes, it is normal: you'd first need to click on a keypoint (which seems to work since one trace is shown in the right panel) and only then assign it a different ID.
> Last point: before moving to tracklet stitching, please make sure detections and assembled animals look good (e.g., using `deeplabcut.create_video_with_all_detections` or `deeplabcut.utils.make_labeled_video.create_video_from_pickled_tracks`. I find it surprising that keypoints on a single mouse are found to belong to 2 individuals.

Great thanks for your suggestions !
Detections were amazing.  I thought the problem was I choose the unappropriate video which was created for checking detections not the original video. Embarrassed, but this was the truth. ,,ԾㅂԾ, after all other possibilities excluded.
