### ISSUE TITLE
API Docs Dropdown is empty on DeepLabCut User Guide (for single animal projects)

### ISSUE THREAD

**Issue by jake-joseph** [DeepLabCut/DeepLabCut#2682] opened 2024-07-19 17:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When trying to view the API Docs in the blue box by pressing the button to view the drop down, it is a small empty gray box.

### Operating System

Linux Ubuntu 22. Tried on firefox, chrome, and edge

### DeepLabCut version

dlc version 

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment] 2024-07-29 11:33
@jake-joseph thanks for letting us know - this is a duplicate of #2675. I'll close this issue and will close the other when the docs are fixed.

**Closed as not planned by n-poulsen** 2024-07-29 11:33 UTC
Labels: documentation
