### ISSUE TITLE
Issues with refine labels not being saved

### ISSUE THREAD

**Issue by neha28wsu** [DeepLabCut/DeepLabCut#687] opened 2020-05-16 18:16 UTC
**Your Operating system and DeepLabCut version**
Ubuntu 16.04 and DeepLabCut version 2.0.5

Please state your operating system, env, and which version of DeepLabCut you are using.
Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut 2.0.5

Please complete the following information about your system:

OS: Ubuntu 16.04
DeepLabCut Version 2.0.5
Browser Firefox

**Describe the problem**
Refined labels are not being saved, so after extracting outliers, doing refine labels and merging dataset if i check labels it appears that changes made by me are not being saved.
This is an example of an outlier frame that was extracted using default values

![img08283labeled](https://user-images.githubusercontent.com/49492309/82126980-6be40300-977e-11ea-8cc6-6cf8a2de31c5.png)

After using refine labels in which i moved last three dots on tail to the center point in the tail and merged data set. then i used check label that gave me this with no changes at all
![img08283](https://user-images.githubusercontent.com/49492309/82127029-b4032580-977e-11ea-928d-ff252ffa557f.png)
 
**How to Reproduce the problem**
Don't know how this can be reproduce i just follow the steps involved in deeplabcut procedure.
Trained my network with 1030000 iterations ,ResNet 101
Analysed my videos extracted outliers, refined labels merge dataset and check labels

**Comment by MMathisLab** [comment] 2020-05-16 19:21
in older versions (your version > 1 year old), if you re-open the `machine-labeled.h5` file into the `refinement GUI ` after you adjusted and saved originally, it would look like nothing was changed, as we do not over-write the "machine labels" (because a human didn't create the labels). Then closing this, overwrites the CollectedData_.hdf file. 

You should upgrade your package, many many new and better features exist now and it's fully backwards compatible.

**Comment by MMathisLab** [comment] 2020-05-20 19:23
any updates @neha28wsu ?

**Comment by neha28wsu** [comment] 2020-05-22 15:01
Hello ,
I'm using updated deeplabcut verion 2.1.4 for check labels and facing the same issue.
Also i would like to mention that docker i'm using has dlc version 2.0.5
Thank you for the help..

**Comment by MMathisLab** [comment] 2020-05-22 15:17
@neha28wsu did you merge_datasets? You can also always build a new container; i.e. make a new image with the latest tag, which is 2.1.8.2

**Comment by MMathisLab** [comment] 2020-05-22 16:09
so the new data is indeed in the `collecteddata.h5` file? i.e. these were outlier frames from novel videos, correct?

**Comment by neha28wsu** [comment] 2020-05-22 16:16
That is correct. I checked it, whether my collecteddata.h5 file is updating or not 
and it was updating.
and outliers were from novel video

**Comment by neha28wsu** [comment] 2020-05-31 22:13
Hello, i was trying to work on my refine label and check label but could not make any progress so i though to make video such that i can explain my issue properly.
i have extracted outliers and i refine them 
[video 1.zip](https://github.com/DeepLabCut/DeepLabCut/files/4708560/video.1.zip)

i then merge dataset and check labels but changes i made to labels were not saved
![img00264](https://user-images.githubusercontent.com/49492309/83363643-06d90180-a369-11ea-980f-8cac0ab1901f.png)

i also checked by making big changes 
[video 2.zip](https://github.com/DeepLabCut/DeepLabCut/files/4708571/video.2.zip)

then i merged dataset and check labels but this time change was saved
![img04643](https://user-images.githubusercontent.com/49492309/83363796-3dfbe280-a36a-11ea-931f-93c0a9846198.png)
 Hope i made it more clear
Thanks in advance

**Comment by MMathisLab** [comment] 2020-05-31 22:43
so it is saving when you merge and run check labels? that would be the expected behavior. I'm not sure what I am to see in the videos though; I see you move the points, but that's it. i.e. I don't see you save, merge, and check labels

**Comment by neha28wsu** [comment] 2020-05-31 23:22
in both videos, i moved the points, saved them merge the data and check labels. i didn't recorded whole thing due to file size issue. 
so in first video when i tried to move them just a little, that kind of changes are not being saved 
but when i tried to make big change as done in video 2 that is being saved
not sure why it is happening

**Comment by MMathisLab** [comment] 2020-06-01 16:53
okay, well it seems to be saving, I will close for now, but let me know if you have further insights!

**Closed as completed by MMathisLab** 2020-06-01 16:53 UTC
